var root, canvas, stage, exportRoot, anim_container, dom_overlay_container, fnStartAnimation;

function init() {
    canvas = document.getElementById("canvas");
    anim_container = document.getElementById("animation_container");
    dom_overlay_container = document.getElementById("dom_overlay_container");
    var comp = AdobeAn.getComposition("06CA646165B9954D8AB99D566BA018F3");
    var lib = comp.getLibrary();
    var loader = new createjs.LoadQueue(false);
    loader.addEventListener("fileload", function (evt) {
        handleFileLoad(evt, comp)
    });
    loader.addEventListener("complete", function (evt) {
        handleComplete(evt, comp)
    });
    var lib = comp.getLibrary();
    loader.loadManifest(lib.properties.manifest);
}

function handleFileLoad(evt, comp) {
    var images = comp.getImages();
    if (evt && (evt.item.type == "image")) {
        images[evt.item.id] = evt.result;
    }
}

function handleComplete(evt, comp) {
    var lib = comp.getLibrary();
    var ss = comp.getSpriteSheet();
    var queue = evt.target;
    var ssMetadata = lib.ssMetadata;
    for (i = 0; i < ssMetadata.length; i++) {
        ss[ssMetadata[i].name] = new createjs.SpriteSheet({
            "images": [queue.getResult(ssMetadata[i].name)],
            "frames": ssMetadata[i].frames
        })
    }
    exportRoot = new lib.mm4splashpage();
    stage = new lib.Stage(canvas);
    stage.enableMouseOver();
    //Registers the "tick" event listener.
    fnStartAnimation = function () {
        stage.addChild(exportRoot);
        createjs.Ticker.setFPS(lib.properties.fps);
        createjs.Ticker.addEventListener("tick", stage);
    }
    //Code to support hidpi screens and responsive scaling.
    AdobeAn.makeResponsive(true, 'both', false, 1, [canvas, anim_container, dom_overlay_container]);
    AdobeAn.compositionLoaded(lib.properties.id);
    fnStartAnimation();
}

(function (cjs, an) {

    var p; // shortcut to reference prototypes
    var lib = {};
    var ss = {};
    var img = {};
    lib.ssMetadata = [
        {
            name: "mm4_splashpage_atlas_",
            frames: [[562, 374, 214, 273], [0, 374, 560, 375], [0, 0, 574, 372]]
        }
];

    
    // symbols:

    (lib.rphomelogo = function () {
        this.initialize(ss["mm4_splashpage_atlas_"]);
        this.gotoAndStop(0);
    }).prototype = p = new cjs.Sprite();



    (lib.rp3normal = function () {
        this.initialize(ss["mm4_splashpage_atlas_"]);
        this.gotoAndStop(1);
    }).prototype = p = new cjs.Sprite();



    (lib.rp4normal = function () {
        this.initialize(ss["mm4_splashpage_atlas_"]);
        this.gotoAndStop(2);
    }).prototype = p = new cjs.Sprite();
    // helper functions:

    function mc_symbol_clone() {
        var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
        clone.gotoAndStop(this.currentFrame);
        clone.paused = this.paused;
        clone.framerate = this.framerate;
        return clone;
    }

    function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
        var prototype = cjs.extend(symbol, cjs.MovieClip);
        prototype.clone = mc_symbol_clone;
        prototype.nominalBounds = nominalBounds;
        prototype.frameBounds = frameBounds;
        return prototype;
    }


    (lib.RpLogo = function (mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});

        // Layer_1
        this.instance = new lib.rphomelogo();
        this.instance.parent = this;
        this.instance.setTransform(-107, -136.5);

        this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

    }).prototype = getMCSymbolPrototype(lib.RpLogo, new cjs.Rectangle(-107, -136.5, 214, 273), null);


    (lib.Rp4Title = function (mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});

        // Layer_1
        this.shape = new cjs.Shape();
        this.shape.graphics.f("#000000").s().p("AFSFNIAAhSIi7AAIAAgiICsjbIA0AAIilDUICCAAIAAhKIAtAAIAABKIA/AAIAAApIg/AAIAABSgAhVFNIAAj+IAuAAIAAD+gAmpFNIAAlPICDAAQBCABAlAdQAlAfAAA3QAAA4glAeQglAfhCABIhTAAIAABlgAl5C+IBSAAQAuAAAYgUQAXgTAAglQAAgkgXgTQgYgUguAAIhSAAgAhUAVQgJgIAAgNQAAgMAJgIQAIgJAOAAQAOAAAIAIQAJAJAAAMQAAAMgIAJQgJAJgOAAQgOAAgIgJgAHAhtQgJgDgGgGIAKgRQAFAEAFADQAGACAHAAQAIAAAGgEQAFgFAFgLIAEgIIg4h/IAYAAIAsBlIAshlIAXAAIg+CLQgGAOgHAIQgGAHgJAEQgIADgJAAQgKAAgIgDgAjShsIAAitIAWAAIAAAUQAIgLAMgFQALgGAPAAQASABAPAIQAOAIAIAOQAJAPAAATQAAAUgJAOQgIAPgOAIQgPAIgSAAQgOAAgLgFQgMgFgIgKIAABBgAimkBQgKAGgFAKQgGAKAAANQAAAOAGAKQAFAKAKAFQAJAGANAAQAMAAAKgGQAJgFAGgKQAFgKABgOQgBgNgFgKQgGgKgJgGQgKgFgMAAQgNAAgJAFgACJihQgQgJgIgOQgJgPAAgTQABgTAIgOQAIgPAOgIQAPgIASgBQATABAOAIQAOAIAIAPQAIAOAAAUIAAADIAAAEIhoAAQADARAMAKQAMAKATAAQAMAAAJgEQAJgEAHgHIANAPQgJAKgNAFQgMAFgQAAQgVAAgPgIgADRjjQgCgQgLgKQgLgKgRAAQgRAAgLAKQgLAKgCAQIBSAAIAAAAgAgFieQgLgGgIgKIAAAUIgWAAIAAiyIAXAAIAABGQAIgKALgGQAKgFAOAAQATABAOAIQAPAIAIAOQAIAPAAATQAAAUgIAOQgIAPgPAIQgOAIgTAAQgOAAgLgFgAgDkBQgJAGgGAKQgFAKgBANQABAOAFAKQAGAKAJAFQAJAGAMAAQAMAAAKgGQAKgFAFgKQAGgKAAgOQAAgNgGgKQgFgKgKgGQgKgFgMAAQgMAAgJAFgAk6ibQgKgCgIgDQgJgEgFgEIAKgSQAIAGAMADQAMAEAMAAQAQAAAHgEQAIgFgBgIQAAgHgFgDQgGgEgJgCIgUgDQgKgCgJgDQgJgEgGgHQgGgHAAgMQAAgSAOgKQAOgKAZgBIARACIAQAEQAIACAFAEIgJASQgJgFgJgDQgKgCgJAAQgPAAgIAFQgHAFAAAIQAAAHAGAEQAGADAJACIATAEQAKABAKAEQAJADAGAHQAFAHABANQgBARgOAKQgPAKgZAAQgLAAgKgCgAnXijQgMgKAAgRQAAgLAFgIQAEgIAMgFQALgFATAAIAkAAIAAgFQAAgPgIgIQgJgIgRAAQgLAAgLAEQgLAEgHAGIgKgRQAKgIAOgEQANgFAQAAQAaAAAOANQAOANAAAaIAABNIgVAAIAAgRQgGAJgLAEQgKAFgPAAQgWAAgNgKgAnBjQQgGACgDAFQgDAEABAGQAAAJAHAGQAHAFAOAAQANAAAJgFQAKgGAEgLIAAgSIgjAAQgMAAgGADgAFqiaIAAh/IAWAAIAAAVQAGgLAMgGQALgGARAAIAAAXIgDgBIgCAAQgTABgLAKQgKALAAAVIAABAgAEHiaIAAh/IAWAAIAAAVQAGgLAMgGQAMgGAQAAIAAAXIgCgBIgDAAQgTABgKAKQgLALAAAVIAABAgAo8iaIAAh/IAWAAIAAAVQAGgLAMgGQAMgGAQAAIAAAXIgCgBIgDAAQgTABgKAKQgLALAAAVIAABAg");
        this.shape.setTransform(0.025, 0.025);

        this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

    }).prototype = getMCSymbolPrototype(lib.Rp4Title, new cjs.Rectangle(-57.2, -33.3, 114.5, 66.69999999999999), null);


    (lib.Rp4Photo = function (mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});

        // Layer_1
        this.instance = new lib.rp4normal();
        this.instance.parent = this;
        this.instance.setTransform(-287, -186);

        this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

    }).prototype = getMCSymbolPrototype(lib.Rp4Photo, new cjs.Rectangle(-287, -186, 574, 372), null);


    (lib.Rp3Title = function (mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});

        // Layer_1
        this.shape = new cjs.Shape();
        this.shape.graphics.f("#000000").s().p("ADVFEQghgKgVgUIAWgmQARARAaAKQAbAJAfABQAmgBAUgQQAVgPAAgcQAAgbgUgQQgUgQgrAAIgbAAIAAghIBVhoIiiAAIAAgpIDeAAIAAAgIhYBsQAyAFAaAaQAZAaAAAnQAAAdgOAXQgOAYgcANQgcAOgrAAQglAAgggLgAg+FLIAAj+IAuAAIAAD+gAmSFLIAAlPICDAAQBCABAlAdQAlAfAAA3QAAA4glAeQglAfhCABIhTAAIAABlgAliC8IBSAAQAuAAAYgUQAXgTAAglQAAgkgXgTQgYgUguAAIhSAAgAg9ATQgJgIAAgMQAAgNAJgIQAIgJAOAAQAOAAAIAIQAJAJAAAMQAAAMgIAJQgJAJgOAAQgOAAgIgJgAHAhvQgJgDgGgGIAKgRQAFAEAFADQAGACAHAAQAIAAAGgEQAFgFAFgLIAEgIIg4h/IAYAAIAsBlIAshlIAXAAIg+CLQgGAOgHAIQgGAHgJAEQgIADgJAAQgKAAgIgDgAjShuIAAitIAWAAIAAAUQAIgLAMgFQALgGAPAAQASABAPAIQAOAIAIAOQAJAPAAATQAAAUgJAOQgIAPgOAIQgPAIgSAAQgOAAgLgFQgMgFgIgKIAABBgAimkDQgKAGgFAKQgGAKAAANQAAAOAGAKQAFAKAKAFQAJAGANAAQAMAAAKgGQAJgFAGgKQAFgKABgOQgBgNgFgKQgGgKgJgGQgKgFgMAAQgNAAgJAFgACJijQgQgJgIgOQgJgPAAgTQABgTAIgOQAIgPAOgIQAPgIASgBQATABAOAIQAOAIAIAPQAIAOAAAUIAAADIAAAEIhoAAQADARAMAKQAMAKATAAQAMAAAJgEQAJgEAHgHIANAPQgJAKgNAFQgMAFgQAAQgVAAgPgIgADRjlQgCgQgLgKQgLgKgRAAQgRAAgLAKQgLAKgCAQIBSAAIAAAAgAgFigQgLgGgIgKIAAAUIgWAAIAAiyIAXAAIAABGQAIgKALgGQAKgFAOAAQATABAOAIQAPAIAIAOQAIAPAAATQAAAUgIAOQgIAPgPAIQgOAIgTAAQgOAAgLgFgAgDkDQgJAGgGAKQgFAKgBANQABAOAFAKQAGAKAJAFQAJAGAMAAQAMAAAKgGQAKgFAFgKQAGgKAAgOQAAgNgGgKQgFgKgKgGQgKgFgMAAQgMAAgJAFgAk6idQgKgCgIgDQgJgEgFgEIAKgSQAIAGAMADQAMAEAMAAQAQAAAHgEQAIgFgBgIQAAgHgFgDQgGgEgJgCIgUgDQgKgCgJgDQgJgEgGgHQgGgHAAgMQAAgSAOgKQAOgKAZgBIARACIAQAEQAIACAFAEIgJASQgJgFgJgDQgKgCgJAAQgPAAgIAFQgHAFAAAIQAAAHAGAEQAGADAJACIATAEQAKABAKAEQAJADAGAHQAFAHABANQgBARgOAKQgPAKgZAAQgLAAgKgCgAnXilQgMgKAAgRQAAgLAFgIQAEgIAMgFQALgFATAAIAkAAIAAgFQAAgPgIgIQgJgIgRAAQgLAAgLAEQgLAEgHAGIgKgRQAKgIAOgEQANgFAQAAQAaAAAOANQAOANAAAaIAABNIgVAAIAAgRQgGAJgLAEQgKAFgPAAQgWAAgNgKgAnBjSQgGACgDAFQgDAEABAGQAAAJAHAGQAHAFAOAAQANAAAJgFQAKgGAEgLIAAgSIgjAAQgMAAgGADgAFqicIAAh/IAWAAIAAAVQAGgLAMgGQALgGARAAIAAAXIgDgBIgCAAQgTABgLAKQgKALAAAVIAABAgAEHicIAAh/IAWAAIAAAVQAGgLAMgGQAMgGAQAAIAAAXIgCgBIgDAAQgTABgKAKQgLALAAAVIAABAgAo8icIAAh/IAWAAIAAAVQAGgLAMgGQAMgGAQAAIAAAXIgCgBIgDAAQgTABgKAKQgLALAAAVIAABAg");
        this.shape.setTransform(0.025, 0.025);

        this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

    }).prototype = getMCSymbolPrototype(lib.Rp3Title, new cjs.Rectangle(-57.2, -33.5, 114.5, 67.1), null);


    (lib.Rp3Photo = function (mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});

        // Layer_1
        this.instance = new lib.rp3normal();
        this.instance.parent = this;
        this.instance.setTransform(-280, -187.5);

        this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

    }).prototype = getMCSymbolPrototype(lib.Rp3Photo, new cjs.Rectangle(-280, -187.5, 560, 375), null);


    (lib.Rp4PhotoBtn = function (mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});

        // Layer_1
        this.rp4PhotoMc = new lib.Rp4Photo();
        this.rp4PhotoMc.name = "rp4PhotoMc";
        this.rp4PhotoMc.parent = this;

        this.timeline.addTween(cjs.Tween.get(this.rp4PhotoMc).wait(1).to({
            scaleX: 0.9826,
            scaleY: 0.9825
        }, 0).wait(2).to({
            scaleX: 1,
            scaleY: 1
        }, 0).wait(1));

    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = new cjs.Rectangle(-287, -186, 574, 372);


    (lib.Rp3PhotoBtn = function (mode, startPosition, loop) {
        this.initialize(mode, startPosition, loop, {});

        // Layer_1
        this.rp3PhotoMc = new lib.Rp3Photo();
        this.rp3PhotoMc.name = "rp3PhotoMc";
        this.rp3PhotoMc.parent = this;

        this.timeline.addTween(cjs.Tween.get(this.rp3PhotoMc).wait(1).to({
            scaleX: 0.9821,
            scaleY: 0.9821
        }, 0).wait(2).to({
            scaleX: 1,
            scaleY: 1
        }, 0).wait(1));

    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = new cjs.Rectangle(-280, -187.5, 560, 375);


    // stage content:
    (lib.mm4splashpage = function (mode, startPosition, loop) {
        if (loop == null) {
            loop = false;
        }
        this.initialize(mode, startPosition, loop, {});

        // timeline functions:
        this.frame_0 = function () {
            // Vul de global variabele root met dit tijdlijn Object (hoofd tijdlijn) 
            root = this;

            var mainTimeline = new TimelineMax({ // create new timeline in GSAP
                delay: 0, // global delay in animation?
                repeat: 0, // global repeat in animation?
            });

            function getMovieClipTimeline() { // create a custom function that builds and returns a textTimeline
                var movieClipTimeline = new TimelineMax( // initialise movieClipTimeline with an TimeLine(Max) instance with options
                    {
                        delay: 0, // main delay in movieClipTimeline animation
                        repeat: 0, // main repeat in movieClipTimeline animation
                        yoyo: true // yoyo the textTimeLine animation?
                    }
                );

                movieClipTimeline
                    .from( // From Tween start chained on previous
                        root.rpLogoSplashTop, // Logo element
                        0.5, // duration in sec
                        { //fromVars start
                            scaleY: 5, // Y from	
                            ease: Power4.easeOut // easing type
                        }, // fromVars end								
                    ) // from Tween end (and chain terminated)


                    .from( // From Tween start
                        root.rp4PhotoBtnSplash, // Logo element
                        0.5, // duration in sec
                        { // fromVars start
                            y: 2000, // from Y-value	
                            ease: Power4.easeOut // easing type 			
                        }, // fromVars end
                        0.25 // add this tween overlapping the previous with 0.5 sec
                    ) // From Tween end (not terminated)


                    .from( // From Tween start chained on previous
                        root.rp3PhotoBtnSplash, // Logo element
                        0.5, // duration in sec
                        { // fromVars start
                            y: 2000, // from Y-value
                            ease: Power4.easeOut // easing type 	
                        }, // fromVars end
                    ); // From Tween end (not terminated)


                return movieClipTimeline; // return the timeLine (not played yet!)
            } // end of the custom function



            mainTimeline // still an empty timeline
                .add(getMovieClipTimeline()) // now add the moviecliptimeline...



            this.rp4PhotoBtnSplash.addEventListener("click", fl_ClickToGoToWebPage);

            function fl_ClickToGoToWebPage() {
                window.open("pages/pi4.html", "_self");
            }



            this.rp3PhotoBtnSplash.addEventListener("click", fl_ClickToGoToWebPage_2);

            function fl_ClickToGoToWebPage_2() {
                window.open("pages/pi3.html", "_self");
            }
        }

        // actions tween:
        this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

        // Logo_top
        this.rpLogoSplashTop = new lib.RpLogo();
        this.rpLogoSplashTop.name = "rpLogoSplashTop";
        this.rpLogoSplashTop.parent = this;
        this.rpLogoSplashTop.setTransform(608.65, 162.5, 0.8696, 0.8696);

        this.timeline.addTween(cjs.Tween.get(this.rpLogoSplashTop).wait(1));

        // Rp3_photo
        this.rp3PhotoBtnSplash = new lib.Rp3PhotoBtn();
        this.rp3PhotoBtnSplash.name = "rp3PhotoBtnSplash";
        this.rp3PhotoBtnSplash.parent = this;
        this.rp3PhotoBtnSplash.setTransform(916, 589.35, 0.8696, 0.8696);
        new cjs.ButtonHelper(this.rp3PhotoBtnSplash, 0, 1, 2, false, new lib.Rp3PhotoBtn(), 3);

        this.timeline.addTween(cjs.Tween.get(this.rp3PhotoBtnSplash).wait(1));

        // Rp4_photo
        this.rp4PhotoBtnSplash = new lib.Rp4PhotoBtn();
        this.rp4PhotoBtnSplash.name = "rp4PhotoBtnSplash";
        this.rp4PhotoBtnSplash.parent = this;
        this.rp4PhotoBtnSplash.setTransform(304.75, 590.55, 0.8696, 0.8696);
        new cjs.ButtonHelper(this.rp4PhotoBtnSplash, 0, 1, 2, false, new lib.Rp4PhotoBtn(), 3);

        this.timeline.addTween(cjs.Tween.get(this.rp4PhotoBtnSplash).wait(1));

        // Mission_text
        this.shape = new cjs.Shape();
        this.shape.graphics.f("#000000").s().p("ARZEFIAAgJIAJABQAMAAAFgOIAEgKIgfhMIANAAIAQArIAHAVIAAAAIAEgMIATg0IAMAAIggBWQgFAMgHAGQgGAFgJAAQgGAAgFgBgApYEGIAAhtIAKAAIABAKIABAAQAEgGAGgDQAGgCAHAAQAPAAAIAKQAJAKAAATQAAASgJAKQgIALgPAAQgHAAgGgDQgGgDgEgFIgBAAIABAMIAAAfgApHCoQgFAGAAAOIAAADQAAAPAFAHQAFAHAMAAQAKAAAFgIQAGgIAAgOQAAgOgGgHQgFgIgKAAQgMAAgFAHgASsDkQgDgCAAgFQAAgFACgCQACgCAEAAQAEAAADACQACACAAAFQAAAEgDADQgCACgEAAQgDAAgCgCgAP3DbQgJgKAAgSQAAgSAJgLQAJgKAPAAQAOAAAIAJQAIAJAAAQIAAAHIg0AAQABANAGAHQAGAHAMAAQAMAAAMgFIAAAKIgLAEIgNABQgRAAgKgLgAQACnQgFAGgBAKIAnAAQAAgKgFgGQgFgGgIAAQgKAAgFAGgANXDPIAAgtIgLAAIAAgGIALgEIAFgQIAHAAIAAARIAVAAIAAAJIgVAAIAAAsQAAAHADAEQADADAGAAIAFAAIAFgBIAAAJIgGABIgGABQgWAAAAgXgAMJDgQgGgGAAgLQAAgWAkgBIANgBIAAgEQAAgJgEgFQgEgEgIAAQgJAAgMAGIgEgJQAGgDAGgBQAHgCAHAAQANAAAHAGQAGAGAAANIAAAzIgIAAIgDgKIAAAAQgGAHgFACQgGADgIAAQgMAAgGgGgAMoDAQgNAAgGAEQgGAEAAAIQAAAGADADQAEADAHAAQAKAAAHgGQAGgFAAgLIAAgHgAK/DbQgKgKAAgSQAAgSAJgLQAJgKAPAAQAOAAAJAJQAIAJAAAQIAAAHIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgLgALICnQgGAGgBAKIAoAAQAAgKgFgGQgFgGgJAAQgJAAgFAGgAJCDcQgJgKAAgTQAAgTAJgKQAJgKARAAIAKABIAJADIgEAJIgIgCIgIgBQgXAAAAAdQAAAOAGAHQAGAIALAAQAJAAAKgEIAAAKQgIAEgLAAQgQAAgJgKgAHRDhIAAgLQAFADAGACIAMABQAJAAAFgDQAFgCAAgGQAAgFgEgDQgEgDgLgEIgPgHQgEgDgCgEQgCgDAAgFQAAgKAHgFQAHgFAOAAQAMAAALAFIgEAJQgLgFgJAAQgIAAgFADQgEACAAAFQAAADACACQABACAEACIANAGQANAEAFAFQAFAFAAAIQAAAKgIAGQgIAGgOAAQgPAAgIgFgAGMDbQgKgKAAgSQAAgSAJgLQAJgKAPAAQAOAAAJAJQAIAJAAAQIAAAHIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgLgAGVCnQgGAGgBAKIAoAAQAAgKgFgGQgFgGgJAAQgJAAgFAGgADTDbQgKgKAAgSQAAgSAJgLQAJgKAPAAQAOAAAJAJQAIAJAAAQIAAAHIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgLgADcCnQgGAGgBAKIAoAAQAAgKgFgGQgFgGgJAAQgJAAgFAGgACGDhIAAgLQAFADAGACIAMABQAJAAAFgDQAFgCAAgGQAAgFgEgDQgEgDgLgEIgPgHQgEgDgCgEQgCgDAAgFQAAgKAHgFQAHgFAOAAQAMAAALAFIgEAJQgLgFgJAAQgIAAgFADQgEACAAAFQAAADACACQABACAEACIANAGQANAEAFAFQAFAFAAAIQAAAKgIAGQgIAGgOAAQgPAAgIgFgAhBDbQgKgKAAgSQAAgSAJgLQAJgKAPAAQAOAAAJAJQAIAJAAAQIAAAHIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgLgAg4CnQgGAGgBAKIAoAAQAAgKgFgGQgFgGgJAAQgJAAgFAGgAjNDPIAAgtIgLAAIAAgGIALgEIAEgQIAHAAIAAARIAWAAIAAAJIgWAAIAAAsQAAAHADAEQADADAGAAIAGAAIAEgBIAAAJIgFABIgHABQgVAAAAgXgAk7DhIAAgLQAGADAGACIAMABQAJAAAFgDQAEgCAAgGQAAgFgDgDQgEgDgLgEIgPgHQgFgDgCgEQgCgDAAgFQAAgKAHgFQAIgFANAAQAMAAAMAFIgEAJQgMgFgJAAQgIAAgEADQgEACAAAFQAAADABACQACACADACIAOAGQANAEAFAFQAEAFAAAIQAAAKgHAGQgIAGgOAAQgPAAgJgFgAl+DhIAAgLQAGADAGACIAMABQAJAAAFgDQAEgCAAgGQAAgFgDgDQgEgDgLgEIgPgHQgFgDgCgEQgCgDAAgFQAAgKAHgFQAIgFANAAQAMAAAMAFIgEAJQgMgFgJAAQgIAAgEADQgEACAAAFQAAADABACQACACADACIAOAGQANAEAFAFQAEAFAAAIQAAAKgHAGQgIAGgOAAQgPAAgJgFgAnDDbQgJgKAAgSQAAgSAJgLQAJgKAPAAQAOAAAIAJQAIAJAAAQIAAAHIg0AAQABANAGAHQAGAHAMAAQAMAAAMgFIAAAKIgLAEIgNABQgRAAgKgLgAm6CnQgFAGgBAKIAnAAQAAgKgFgGQgFgGgIAAQgKAAgFAGgArrDbQgKgKAAgSQAAgSAJgLQAJgKAPAAQAOAAAJAJQAIAJAAAQIAAAHIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgLgAriCnQgGAGgBAKIAoAAQAAgKgFgGQgFgGgJAAQgJAAgFAGgAteDhQgHgFgFgJQgEgJAAgLQAAgTAJgKQAKgKAQAAQAQAAAJAKQAJALAAASQAAASgJAKQgJALgRAAQgKAAgIgFgAtcCpQgGAHAAAPQAAAOAGAIQAFAHAMAAQALAAAGgHQAFgIAAgOQAAgPgFgHQgGgIgLAAQgMAAgFAIgAuaDPIAAgtIgLAAIAAgGIALgEIAEgQIAHAAIAAARIAWAAIAAAJIgWAAIAAAsQAAAHADAEQADADAGAAIAGAAIAEgBIAAAJIgFABIgHABQgVAAAAgXgAwSDcQgIgLAAgSQAAgTAIgKQAJgKAOAAQAQAAAIALIABAAIgBgLIAAgeIALAAIAABqIgJAAIgBgKIgBAAQgIAMgQAAQgOAAgJgKgAwJCpQgFAIAAAOQAAAOAFAIQAGAHAKAAQALAAAGgGQAFgHAAgOIAAgCQAAgQgFgHQgGgHgLAAQgKAAgGAIgAy5DgQgHgGAAgLQAAgWAlgBIAMgBIAAgEQAAgJgDgFQgEgEgJAAQgJAAgMAGIgDgJQAFgDAHgBQAGgCAHAAQAOAAAGAGQAHAGAAANIAAAzIgJAAIgCgKIgBAAQgFAHgGACQgGADgIAAQgLAAgGgGgAyaDAQgOAAgGAEQgGAEAAAIQAAAGAEADQAEADAGAAQALAAAGgGQAGgFAAgLIAAgHgARBDkIAAhqIALAAIAABqgAO8DkIgdhLIAMAAIARAtIAGAUIABAAIAEgPIASgyIANAAIgdBLgAOIDkIAAhLIALAAIAABLgAKADkIAAhLIAJAAIACAOIAAAAQAEgHAGgEQAGgEAHAAIAJABIgBAKIgJgBQgJAAgGAHQgHAIAAALIAAAogAFQDkIgchLIAMAAIAQAtIAHAUIAAAAIAFgPIASgyIAMAAIgcBLgAEcDkIAAhqIAMAAIAABqgABnDkIAAgxQAAgJgEgEQgEgFgIAAQgKAAgFAGQgFAHAAAMIAAAqIgMAAIAAgxQAAgJgEgEQgDgFgJAAQgKAAgFAHQgFAGAAAPIAAAnIgMAAIAAhLIAKAAIABAKIABAAQADgFAGgDQAGgDAHAAQASAAAFAMIABAAQADgFAHgEQAGgDAIAAQANAAAGAGQAHAHAAAOIAAAxgAhpDkIAAgwQAAgKgEgEQgFgFgJAAQgLAAgGAHQgFAGAAAPIAAAnIgMAAIAAhqIAMAAIAAAgIgBAJIABAAQADgFAGgDQAHgDAIAAQANAAAHAGQAHAHAAAOIAAAxgAoCDkIAAhLIAKAAIABAOIABAAQAEgHAGgEQAGgEAHAAIAJABIgCAKIgIgBQgJAAgHAHQgGAIAAALIAAAogAp0DkIgVgeIgVAeIgNAAIAbgmIgaglIANAAIAUAdIAUgdIANAAIgaAlIAbAmgAw4DkIAAgwQAAgKgEgEQgFgFgJAAQgLAAgGAHQgFAGAAAPIAAAnIgMAAIAAhLIAKAAIABAKIABAAQADgFAHgDQAGgDAIAAQANAAAHAGQAHAHAAAOIAAAxgAOJCKQgCgBAAgEQAAgEACgCQACgCADAAQAAAAABAAQABAAAAABQABAAAAAAQABAAAAABQACACAAAEQAAAEgCABQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgDAAgCgCgEAjpABHIAAhsIAKAAIABAKIABAAQAEgGAGgDQAGgDAHAAQAPAAAIAKQAJALAAASQAAASgJAKQgIAKgPAAQgHAAgGgDQgGgCgEgGIgBAAIABANIAAAfgEAj6gAXQgFAHAAAOIAAACQAAAPAFAHQAFAHAMAAQAKAAAFgIQAGgIAAgNQAAgOgGgIQgFgHgKAAQgMAAgFAGgAMyBBQgIgFAAgKQAAgHAFgFQAEgFAIgCQgDgBgCgDQgCgDAAgEQAAgEADgDQACgDAEgDQgFgCgEgFQgEgGAAgHQAAgMAIgHQAHgHAOAAQAGAAAEACIAaAAIAAAHIgOABIAEAHQABAEAAAEQAAALgHAGQgIAHgNAAIgGgBQgHAEAAAGQAAADACABQADACAGAAIANAAQAMAAAHAFQAGAFAAAKQAAAMgKAHQgKAHgTAAQgPAAgIgGgAM6AnQgFADAAAHQAAAGAGAEQAFADAJAAQAPAAAHgEQAGgFAAgHQAAgGgDgDQgEgCgLAAIgNAAQgIAAgEAEgANAgaQgEAEAAAJQAAAIAEAEQAEADAIAAQARAAAAgQQAAgRgRAAQgIAAgEAFgAhBBBQgIgFAAgKQAAgHAEgFQAFgFAIgCQgDgBgCgDQgCgDAAgEQAAgEACgDQACgDAFgDQgGgCgDgFQgEgGAAgHQAAgMAHgHQAIgHANAAQAGAAAFACIAaAAIAAAHIgOABIADAHQACAEAAAEQAAALgIAGQgHAHgNAAIgHgBQgHAEAAAGQAAADADABQACACAGAAIAOAAQAMAAAGAFQAHAFAAAKQAAAMgKAHQgKAHgTAAQgPAAgIgGgAg6AnQgEADAAAHQAAAGAFAEQAFADAKAAQAOAAAHgEQAHgFAAgHQAAgGgEgDQgEgCgKAAIgOAAQgHAAgFAEgAg0gaQgEAEAAAJQAAAIAFAEQAEADAIAAQARAAAAgQQAAgRgRAAQgIAAgFAFgApLBBQgIgFAAgKQAAgHAFgFQAEgFAIgCQgDgBgCgDQgCgDAAgEQAAgEADgDQACgDAEgDQgFgCgEgFQgEgGAAgHQAAgMAIgHQAHgHAOAAQAGAAAEACIAaAAIAAAHIgOABIAEAHQABAEAAAEQAAALgHAGQgIAHgNAAIgGgBQgHAEAAAGQAAADACABQADACAGAAIANAAQAMAAAHAFQAGAFAAAKQAAAMgKAHQgKAHgTAAQgPAAgIgGgApDAnQgFADAAAHQAAAGAGAEQAFADAJAAQAPAAAHgEQAGgFAAgHQAAgGgDgDQgEgCgLAAIgNAAQgIAAgEAEgAo9gaQgEAEAAAJQAAAIAEAEQAEADAIAAQARAAAAgQQAAgRgRAAQgIAAgEAFgAuhBHIAAhsIAKAAIABAKIABAAQAEgGAGgDQAGgDAHAAQAPAAAIAKQAJALAAASQAAASgJAKQgIAKgPAAQgHAAgGgDQgGgCgEgGIgBAAIABANIAAAfgAuQgXQgFAHAAAOIAAACQAAAPAFAHQAFAHAMAAQAKAAAFgIQAGgIAAgNQAAgOgGgIQgFgHgKAAQgMAAgFAGgA8pBHIAAhsIAKAAIABAKIABAAQAEgGAGgDQAGgDAHAAQAPAAAIAKQAJALAAASQAAASgJAKQgIAKgPAAQgHAAgGgDQgGgCgEgGIgBAAIABANIAAAfgA8YgXQgFAHAAAOIAAACQAAAPAFAHQAFAHAMAAQAKAAAFgIQAGgIAAgNQAAgOgGgIQgFgHgKAAQgMAAgFAGgEg4gABHIAAhsIAKAAIABAKIABAAQAEgGAGgDQAGgDAHAAQAPAAAIAKQAJALAAASQAAASgJAKQgIAKgPAAQgHAAgGgDQgGgCgEgGIgBAAIABANIAAAfgEg4PgAXQgFAHAAAOIAAACQAAAPAFAHQAFAHAMAAQAKAAAFgIQAGgIAAgNQAAgOgGgIQgFgHgKAAQgMAAgFAGgEg8aABHIAAhsIAKAAIABAKIABAAQAEgGAGgDQAGgDAHAAQAPAAAIAKQAJALAAASQAAASgJAKQgIAKgPAAQgHAAgGgDQgGgCgEgGIgBAAIABANIAAAfgEg8JgAXQgFAHAAAOIAAACQAAAPAFAHQAFAHAMAAQAKAAAFgIQAGgIAAgNQAAgOgGgIQgFgHgKAAQgMAAgFAGgEBCLAA3IAEgSIADgRIAMAAIABACIgFAQIgHARgAZ7A3IAEgSIADgRIAMAAIABACIgFAQIgHARgEA/GAAcQgKgKAAgSQAAgRAJgLQAJgLAPAAQAOAAAJAKQAIAJAAAPIAAAGIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgKgEA/PgAXQgGAGgBAKIAoAAQAAgLgFgGQgFgFgJAAQgJAAgFAGgEA85AAPIAAgsIgLAAIAAgFIALgFIAFgQIAHAAIAAASIAVAAIAAAIIgVAAIAAAsQAAAGADAEQADAEAGAAIAFgBIAFgBIAAAJIgGACIgGAAQgWAAAAgXgEA7LAAhQgHgEgFgJQgEgJAAgLQAAgSAJgLQAKgKAQAAQAQAAAJALQAJAKAAASQAAARgJALQgJAKgRAAQgKAAgIgFgEA7NgAWQgGAIAAAOQAAANAGAIQAFAIAMAAQALAAAGgIQAFgHAAgOQAAgOgFgIQgGgHgLAAQgMAAgFAHgEA6PAAPIAAgsIgLAAIAAgFIALgFIAEgQIAHAAIAAASIAWAAIAAAIIgWAAIAAAsQAAAGADAEQADAEAGAAIAGgBIAEgBIAAAJIgFACIgHAAQgVAAAAgXgEA3mAAcQgJgKAAgSQAAgRAJgLQAJgLAPAAQAOAAAIAKQAIAJAAAPIAAAGIg0AAQABANAGAHQAGAHAMAAQAMAAAMgFIAAAKIgLAEIgNABQgRAAgKgKgEA3vgAXQgFAGgBAKIAnAAQAAgLgFgGQgFgFgIAAQgKAAgFAGgEA2wAAPIAAgsIgLAAIAAgFIALgFIAFgQIAHAAIAAASIAVAAIAAAIIgVAAIAAAsQAAAGADAEQADAEAGAAIAFgBIAFgBIAAAJIgGACIgGAAQgWAAAAgXgEA1+AAPIAAgsIgLAAIAAgFIALgFIAFgQIAHAAIAAASIAVAAIAAAIIgVAAIAAAsQAAAGADAEQADAEAGAAIAFgBIAFgBIAAAJIgGACIgGAAQgWAAAAgXgEA0wAAgQgGgFAAgLQAAgWAkgBIANAAIAAgFQAAgJgEgEQgEgEgIAAQgJAAgMAFIgEgIQAGgDAGgCQAHgCAHAAQANAAAHAGQAGAGAAANIAAAzIgIAAIgDgLIAAAAQgGAHgFADQgGACgIAAQgMAAgGgGgEA1PAAAQgNABgGAEQgGADAAAIQAAAGADADQAEAEAHAAQAKAAAHgGQAGgGAAgKIAAgHgEAxXAAPIAAgsIgLAAIAAgFIALgFIAFgQIAHAAIAAASIAVAAIAAAIIgVAAIAAAsQAAAGADAEQADAEAGAAIAFgBIAFgBIAAAJIgGACIgGAAQgWAAAAgXgEAwJAAgQgGgFAAgLQAAgWAkgBIANAAIAAgFQAAgJgEgEQgEgEgIAAQgJAAgMAFIgEgIQAGgDAGgCQAHgCAHAAQANAAAHAGQAGAGAAANIAAAzIgIAAIgDgLIAAAAQgGAHgFADQgGACgIAAQgMAAgGgGgEAwoAAAQgNABgGAEQgGADAAAIQAAAGADADQAEAEAHAAQAKAAAHgGQAGgGAAgKIAAgHgEAuCAAPIAAgsIgLAAIAAgFIALgFIAEgQIAHAAIAAASIAWAAIAAAIIgWAAIAAAsQAAAGADAEQADAEAGAAIAGgBIAEgBIAAAJIgFACIgHAAQgVAAAAgXgEAsUAAhIAAgKQAGADAGABIAMACQAJAAAFgDQAEgDAAgGQAAgEgDgDQgEgDgLgFIgPgFQgFgDgCgEQgCgEAAgFQAAgJAHgFQAIgGANAAQAMAAAMAFIgEAJQgMgEgJAAQgIAAgEACQgEADAAAEQAAADABACQACADADABIAOAGQANAFAFAEQAEAFAAAHQAAALgHAFQgIAGgOAAQgPAAgJgFgEApNAAcQgKgKAAgSQAAgRAJgLQAJgLAPAAQAOAAAJAKQAIAJAAAPIAAAGIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgKgEApWgAXQgGAGgBAKIAoAAQAAgLgFgGQgFgFgJAAQgJAAgFAGgEAnjAAjQgGgCgEgGIgBAAIgDAKIgIAAIAAhqIAMAAIAAAaIgBAQIABAAQAIgMAPAAQAPAAAIAKQAJALAAASQAAASgJAKQgIAKgPAAQgHAAgGgDgEAnegAWQgFAGAAAQQAAAPAFAHQAFAHAMAAQAKAAAGgIQAFgIAAgNQAAgPgFgHQgGgHgKAAQgMAAgFAHgEAmFAAhQgIgEgEgJQgEgJAAgLQAAgSAJgLQAJgKAQAAQAQAAAJALQAKAKAAASQAAARgKALQgJAKgQAAQgKAAgIgFgEAmGgAWQgGAIAAAOQAAANAGAIQAGAIALAAQALAAAGgIQAGgHAAgOQAAgOgGgIQgGgHgLAAQgLAAgGAHgEAh7AAcQgJgKAAgSQAAgRAJgLQAJgLAPAAQAOAAAIAKQAIAJAAAPIAAAGIg0AAQABANAGAHQAGAHAMAAQAMAAAMgFIAAAKIgLAEIgNABQgRAAgKgKgEAiEgAXQgFAGgBAKIAnAAQAAgLgFgGQgFgFgIAAQgKAAgFAGgAfDAhQgHgEgFgJQgEgJAAgLQAAgSAJgLQAKgKAQAAQAQAAAJALQAJAKAAASQAAARgJALQgJAKgRAAQgKAAgIgFgAfFgWQgGAIAAAOQAAANAGAIQAFAIAMAAQALAAAGgIQAFgHAAgOQAAgOgFgIQgGgHgLAAQgMAAgFAHgAdvAhIAAgKQAGADAGABIAMACQAJAAAFgDQAEgDAAgGQAAgEgDgDQgEgDgLgFIgPgFQgFgDgCgEQgCgEAAgFQAAgJAHgFQAIgGANAAQAMAAAMAFIgEAJQgMgEgJAAQgIAAgEACQgEADAAAEQAAADABACQACADADABIAOAGQANAFAFAEQAEAFAAAHQAAALgHAFQgIAGgOAAQgPAAgJgFgAcHAhQgIgEgEgJQgEgJAAgLQAAgSAJgLQAJgKAQAAQAQAAAJALQAKAKAAASQAAARgKALQgJAKgQAAQgKAAgIgFgAcIgWQgGAIAAAOQAAANAGAIQAGAIALAAQALAAAGgIQAGgHAAgOQAAgOgGgIQgGgHgLAAQgLAAgGAHgAbKAPIAAgsIgLAAIAAgFIALgFIAFgQIAHAAIAAASIAVAAIAAAIIgVAAIAAAsQAAAGADAEQADAEAGAAIAFgBIAFgBIAAAJIgGACIgGAAQgWAAAAgXgAW2AhQgHgEgFgJQgEgJAAgLQAAgSAJgLQAKgKAQAAQAQAAAJALQAJAKAAASQAAARgJALQgJAKgRAAQgKAAgIgFgAW4gWQgGAIAAAOQAAANAGAIQAFAIAMAAQALAAAGgIQAFgHAAgOQAAgOgFgIQgGgHgLAAQgMAAgFAHgASWAhQgHgEgFgJQgEgJAAgLQAAgSAJgLQAKgKAQAAQAQAAAJALQAJAKAAASQAAARgJALQgJAKgRAAQgKAAgIgFgASYgWQgGAIAAAOQAAANAGAIQAFAIAMAAQALAAAGgIQAFgHAAgOQAAgOgFgIQgGgHgLAAQgMAAgFAHgAPvAhIAAgKQAFADAGABIAMACQAJAAAFgDQAFgDAAgGQAAgEgEgDQgEgDgLgFIgPgFQgEgDgCgEQgCgEAAgFQAAgJAHgFQAHgGAOAAQAMAAALAFIgEAJQgLgEgJAAQgIAAgFACQgEADAAAEQAAADACACQABADAEABIANAGQANAFAFAEQAFAFAAAHQAAALgIAFQgIAGgOAAQgPAAgIgFgAOqAcQgKgKAAgSQAAgRAJgLQAJgLAPAAQAOAAAJAKQAIAJAAAPIAAAGIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgKgAOzgXQgGAGgBAKIAoAAQAAgLgFgGQgFgFgJAAQgJAAgFAGgALrAhQgHgEgFgJQgEgJAAgLQAAgSAJgLQAKgKAQAAQAQAAAJALQAJAKAAASQAAARgJALQgJAKgRAAQgKAAgIgFgALtgWQgGAIAAAOQAAANAGAIQAFAIAMAAQALAAAGgIQAFgHAAgOQAAgOgFgIQgGgHgLAAQgMAAgFAHgAJzAhQgIgEgEgJQgEgJAAgLQAAgSAJgLQAJgKAQAAQAQAAAJALQAKAKAAASQAAARgKALQgJAKgQAAQgKAAgIgFgAJ0gWQgGAIAAAOQAAANAGAIQAGAIALAAQALAAAGgIQAGgHAAgOQAAgOgGgIQgGgHgLAAQgLAAgGAHgAF9AcQgJgKAAgSQAAgSAJgLQAJgKARAAIALABIAIADIgDAKIgIgDIgIgBQgXAAAAAdQAAANAGAIQAFAHALAAQAJAAAKgEIAAAKQgHAEgMAAQgQAAgJgKgAEvAcQgKgKAAgSQAAgRAJgLQAJgLAPAAQAOAAAJAKQAIAJAAAPIAAAGIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgKgAE4gXQgGAGgBAKIAoAAQAAgLgFgGQgFgFgJAAQgJAAgFAGgAD4APIAAgsIgLAAIAAgFIALgFIAFgQIAHAAIAAASIAVAAIAAAIIgVAAIAAAsQAAAGADAEQADAEAGAAIAFgBIAFgBIAAAJIgGACIgGAAQgWAAAAgXgABiAgQgGgFAAgLQAAgWAkgBIANAAIAAgFQAAgJgEgEQgEgEgIAAQgJAAgMAFIgEgIQAGgDAGgCQAHgCAHAAQANAAAHAGQAGAGAAANIAAAzIgIAAIgDgLIAAAAQgGAHgFADQgGACgIAAQgMAAgGgGgACBAAQgNABgGAEQgGADAAAIQAAAGADADQAEAEAHAAQAKAAAHgGQAGgGAAgKIAAgHgAAxAPIAAgsIgLAAIAAgFIALgFIAEgQIAHAAIAAASIAWAAIAAAIIgWAAIAAAsQAAAGADAEQADAEAGAAIAGgBIAEgBIAAAJIgFACIgHAAQgVAAAAgXgAi1AcQgIgKAAgSQAAgSAIgLQAIgKAPAAQAPAAAIALIABAAIgBgKIAAgfIAMAAIAABqIgJAAIgCgKIgBAAQgIALgPAAQgPAAgIgKgAisgVQgGAHAAAOQAAAOAGAHQAFAIAKAAQAMAAAFgHQAFgGAAgOIAAgCQAAgQgFgGQgFgHgMAAQgKAAgFAIgAkwAcQgIgKAAgSQAAgSAIgLQAJgKAOAAQAQAAAIALIABAAIgBgKIAAgfIALAAIAABqIgJAAIgBgKIgBAAQgIALgQAAQgOAAgJgKgAkngVQgFAHAAAOQAAAOAFAHQAGAIAKAAQALAAAGgHQAFgGAAgOIAAgCQAAgQgFgGQgGgHgLAAQgKAAgGAIgAnXAgQgHgFAAgLQAAgWAlgBIAMAAIAAgFQAAgJgDgEQgEgEgJAAQgJAAgMAFIgDgIQAFgDAHgCQAGgCAHAAQAOAAAGAGQAHAGAAANIAAAzIgJAAIgCgLIgBAAQgFAHgGADQgGACgIAAQgLAAgGgGgAm4AAQgOABgGAEQgGADAAAIQAAAGAEADQAEAEAGAAQALAAAGgGQAGgGAAgKIAAgHgAr0APIAAgsIgLAAIAAgFIALgFIAFgQIAHAAIAAASIAVAAIAAAIIgVAAIAAAsQAAAGADAEQADAEAGAAIAFgBIAFgBIAAAJIgGACIgGAAQgWAAAAgXgAtFAgQgGgHAAgOIAAgwIALAAIAAAvQAAAKAEAEQAEAFAJAAQAMAAAGgHQAFgGAAgPIAAgmIALAAIAABKIgJAAIgCgKIAAAAQgEAFgGADQgGADgIAAQgOAAgHgGgAxsAhQgIgEgEgJQgEgJAAgLQAAgSAJgLQAJgKAQAAQAQAAAJALQAKAKAAASQAAARgKALQgJAKgQAAQgKAAgIgFgAxrgWQgGAIAAAOQAAANAGAIQAGAIALAAQALAAAGgIQAGgHAAgOQAAgOgGgIQgGgHgLAAQgLAAgGAHgAy2AcQgJgKAAgSQAAgSAJgLQAJgKARAAIAKABIAJADIgEAKIgIgDIgIgBQgXAAAAAdQAAANAGAIQAGAHALAAQAJAAAKgEIAAAKQgIAEgLAAQgQAAgJgKgA1YAhQgHgEgFgJQgEgJAAgLQAAgSAJgLQAKgKAQAAQAQAAAJALQAJAKAAASQAAARgJALQgJAKgRAAQgKAAgIgFgA1WgWQgGAIAAAOQAAANAGAIQAFAIAMAAQALAAAGgIQAFgHAAgOQAAgOgFgIQgGgHgLAAQgMAAgFAHgA4LAcQgKgKAAgSQAAgRAJgLQAJgLAPAAQAOAAAJAKQAIAJAAAPIAAAGIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgKgA4CgXQgGAGgBAKIAoAAQAAgLgFgGQgFgFgJAAQgJAAgFAGgA7HAhQgHgEgFgJQgEgJAAgLQAAgSAJgLQAKgKAQAAQAQAAAJALQAJAKAAASQAAARgJALQgJAKgRAAQgKAAgIgFgA7FgWQgGAIAAAOQAAANAGAIQAFAIAMAAQALAAAGgIQAFgHAAgOQAAgOgFgIQgGgHgLAAQgMAAgFAHgA+XAcQgJgKAAgSQAAgRAJgLQAJgLAPAAQAOAAAIAKQAIAJAAAPIAAAGIg0AAQABANAGAHQAGAHAMAAQAMAAAMgFIAAAKIgLAEIgNABQgRAAgKgKgA+OgXQgFAGgBAKIAnAAQAAgLgFgGQgFgFgIAAQgKAAgFAGgEggjAAPIAAgsIgLAAIAAgFIALgFIAFgQIAHAAIAAASIAVAAIAAAIIgVAAIAAAsQAAAGADAEQADAEAGAAIAFgBIAFgBIAAAJIgGACIgGAAQgWAAAAgXgEgiQAAhIAAgKQAFADAGABIAMACQAJAAAFgDQAFgDAAgGQAAgEgEgDQgEgDgLgFIgPgFQgEgDgCgEQgCgEAAgFQAAgJAHgFQAHgGAOAAQAMAAALAFIgEAJQgLgEgJAAQgIAAgFACQgEADAAAEQAAADACACQABADAEABIANAGQANAFAFAEQAFAFAAAHQAAALgIAFQgIAGgOAAQgPAAgIgFgEgjTAAhIAAgKQAFADAGABIAMACQAJAAAFgDQAFgDAAgGQAAgEgEgDQgEgDgLgFIgPgFQgEgDgCgEQgCgEAAgFQAAgJAHgFQAHgGAOAAQAMAAALAFIgEAJQgLgEgJAAQgIAAgFACQgEADAAAEQAAADACACQABADAEABIANAGQANAFAFAEQAFAFAAAHQAAALgIAFQgIAGgOAAQgPAAgIgFgEgkYAAcQgKgKAAgSQAAgRAJgLQAJgLAPAAQAOAAAJAKQAIAJAAAPIAAAGIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgKgEgkPgAXQgGAGgBAKIAoAAQAAgLgFgGQgFgFgJAAQgJAAgFAGgEgn6AAgQgHgFAAgLQAAgWAlgBIAMAAIAAgFQAAgJgDgEQgEgEgJAAQgJAAgMAFIgDgIQAFgDAHgCQAGgCAHAAQAOAAAGAGQAHAGAAANIAAAzIgJAAIgCgLIgBAAQgFAHgGADQgGACgIAAQgLAAgGgGgEgnbAAAQgOABgGAEQgGADAAAIQAAAGAEADQAEAEAGAAQALAAAGgGQAGgGAAgKIAAgHgEgq/AAhQgHgEgFgJQgEgJAAgLQAAgSAJgLQAKgKAQAAQAQAAAJALQAJAKAAASQAAARgJALQgJAKgRAAQgKAAgIgFgEgq9gAWQgGAIAAAOQAAANAGAIQAFAIAMAAQALAAAGgIQAFgHAAgOQAAgOgFgIQgGgHgLAAQgMAAgFAHgEgr7AAPIAAgsIgLAAIAAgFIALgFIAEgQIAHAAIAAASIAWAAIAAAIIgWAAIAAAsQAAAGADAEQADAEAGAAIAGgBIAEgBIAAAJIgFACIgHAAQgVAAAAgXgEgtqAAcQgKgKAAgSQAAgRAJgLQAJgLAPAAQAOAAAJAKQAIAJAAAPIAAAGIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgKgEgthgAXQgGAGgBAKIAoAAQAAgLgFgGQgFgFgJAAQgJAAgFAGgEgvUAAjQgGgCgEgGIgBAAIgCAKIgIAAIAAhqIALAAIAAAaIAAAQIAAAAQAIgMAQAAQAPAAAIAKQAIALAAASQAAASgIAKQgJAKgOAAQgIAAgGgDgEgvZgAWQgFAGAAAQQAAAPAFAHQAGAHALAAQALAAAFgIQAFgIAAgNQAAgPgFgHQgFgHgLAAQgLAAgGAHgEgw3AAgQgGgFAAgLQAAgWAkgBIANAAIAAgFQAAgJgEgEQgEgEgIAAQgJAAgMAFIgEgIQAGgDAGgCQAHgCAHAAQANAAAHAGQAGAGAAANIAAAzIgIAAIgDgLIAAAAQgGAHgFADQgGACgIAAQgMAAgGgGgEgwYAAAQgNABgGAEQgGADAAAIQAAAGADADQAEAEAHAAQAKAAAHgGQAGgGAAgKIAAgHgEgymAAcQgJgKAAgSQAAgRAJgLQAJgLAPAAQAOAAAIAKQAIAJAAAPIAAAGIg0AAQABANAGAHQAGAHAMAAQAMAAAMgFIAAAKIgLAEIgNABQgRAAgKgKgEgydgAXQgFAGgBAKIAnAAQAAgLgFgGQgFgFgIAAQgKAAgFAGgEg0yAAgQgGgFAAgLQAAgWAkgBIANAAIAAgFQAAgJgEgEQgEgEgIAAQgJAAgMAFIgEgIQAGgDAGgCQAHgCAHAAQANAAAHAGQAGAGAAANIAAAzIgIAAIgDgLIAAAAQgGAHgFADQgGACgIAAQgMAAgGgGgEg0TAAAQgNABgGAEQgGADAAAIQAAAGADADQAEAEAHAAQAKAAAHgGQAGgGAAgKIAAgHgEg2hAAcQgJgKAAgSQAAgRAJgLQAJgLAPAAQAOAAAIAKQAIAJAAAPIAAAGIg0AAQABANAGAHQAGAHAMAAQAMAAAMgFIAAAKIgLAEIgNABQgRAAgKgKgEg2YgAXQgFAGgBAKIAnAAQAAgLgFgGQgFgFgIAAQgKAAgFAGgEg5pAAhQgHgEgFgJQgEgJAAgLQAAgSAJgLQAKgKAQAAQAQAAAJALQAJAKAAASQAAARgJALQgJAKgRAAQgKAAgIgFgEg5ngAWQgGAIAAAOQAAANAGAIQAFAIAMAAQALAAAGgIQAFgHAAgOQAAgOgFgIQgGgHgLAAQgMAAgFAHgEg6+AAcQgKgKAAgSQAAgRAJgLQAJgLAPAAQAOAAAJAKQAIAJAAAPIAAAGIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgKgEg61gAXQgGAGgBAKIAoAAQAAgLgFgGQgFgFgJAAQgJAAgFAGgEg+IAAcQgJgKAAgSQAAgRAJgLQAJgLAPAAQAOAAAIAKQAIAJAAAPIAAAGIg0AAQABANAGAHQAGAHAMAAQAMAAAMgFIAAAKIgLAEIgNABQgRAAgKgKgEg9/gAXQgFAGgBAKIAnAAQAAgLgFgGQgFgFgIAAQgKAAgFAGgEhAPAAhQgIgEgEgJQgEgJAAgLQAAgSAJgLQAJgKAQAAQAQAAAJALQAKAKAAASQAAARgKALQgJAKgQAAQgKAAgIgFgEhAOgAWQgGAIAAAOQAAANAGAIQAGAIALAAQALAAAGgIQAGgHAAgOQAAgOgGgIQgGgHgLAAQgLAAgGAHgEBBvAAlIAAgwQAAgJgEgFQgEgEgIAAQgKAAgFAGQgFAGAAANIAAApIgMAAIAAgwQAAgJgEgFQgDgEgJAAQgKAAgFAGQgFAHAAAOIAAAnIgMAAIAAhKIAKAAIABAKIABAAQADgGAGgDQAGgDAHAAQASAAAFANIABAAQADgGAHgDQAGgEAIAAQANAAAGAHQAHAGAAAPIAAAwgEA+eAAlIAAgwQAAgJgEgFQgFgEgJAAQgLAAgGAGQgFAHAAAOIAAAnIgMAAIAAhqIAMAAIAAAgIgBAKIABAAQADgFAGgEQAHgDAIAAQANAAAHAHQAHAGAAAPIAAAwgEA4wAAlIAAhKIAJAAIACANIAAAAQAEgHAGgEQAGgEAHAAIAJABIgBALIgJgBQgJAAgGAHQgHAHAAALIAAAogEA0MAAlIAAgwQAAgJgEgFQgEgEgIAAQgKAAgFAGQgFAGAAANIAAApIgMAAIAAgwQAAgJgEgFQgDgEgJAAQgKAAgFAGQgFAHAAAOIAAAnIgMAAIAAhKIAKAAIABAKIABAAQADgGAGgDQAGgDAHAAQASAAAFANIABAAQADgGAHgDQAGgEAIAAQANAAAGAHQAHAGAAAPIAAAwgEAvmAAlIAAgwQAAgJgEgFQgFgEgJAAQgLAAgGAGQgFAHAAAOIAAAnIgMAAIAAhqIAMAAIAAAgIgBAKIABAAQADgFAGgEQAHgDAIAAQANAAAHAHQAHAGAAAPIAAAwgEAr2AAlIAAgwQAAgJgEgFQgEgEgIAAQgKAAgFAGQgFAGAAANIAAApIgMAAIAAgwQAAgJgEgFQgDgEgJAAQgKAAgFAGQgFAHAAAOIAAAnIgMAAIAAhKIAKAAIABAKIABAAQADgGAGgDQAGgDAHAAQASAAAFANIABAAQADgGAHgDQAGgEAIAAQANAAAGAHQAHAGAAAPIAAAwgEAokAAlIAAhqIALAAIAABqgEAk/AAlIAAhKIAKAAIABANIABAAQAEgHAGgEQAGgEAHAAIAJABIgCALIgIgBQgJAAgHAHQgGAHAAALIAAAogEAhAAAlIgdhKIAMAAIARArIAGAUIABAAIAEgPIASgwIANAAIgdBKgEAgMAAlIAAhqIALAAIAABqgAZnAlIgagkIgJAIIAAAcIgLAAIAAhqIALAAIAAA5IAAALIAAAAIAJgLIAYgZIAOAAIgfAgIAhAqgAX/AlIAAhKIAKAAIABANIABAAQAEgHAGgEQAGgEAHAAIAJABIgCALIgIgBQgJAAgHAHQgGAHAAALIAAAogAV7AlIgOgrIgFgTIAAAAIgFATIgOArIgOAAIgUhKIAMAAIALAqIAEAUIABAAIACgKIADgKIAOgqIAMAAIAOAqQAEAMABAIIAAAAIACgIIAOg2IAMAAIgVBKgATfAlIAAhKIAKAAIABANIABAAQAEgHAGgEQAGgEAHAAIAJABIgCALIgIgBQgJAAgHAHQgGAHAAALIAAAogARfAlIAAhCIgOAAIAAgFIAOgEIAAgEQAAgcAYAAQAGAAAIADIgDAJQgHgCgEAAQgHAAgDAEQgDAEAAAKIAAAFIATAAIAAAIIgTAAIAABCgAOBAlIAAhKIALAAIAABKgAK8AlIAAhqIALAAIAABqgAJEAlIAAgwQAAgJgEgFQgEgEgJAAQgMAAgFAGQgGAHAAAOIAAAnIgLAAIAAhKIAJAAIACAKIAAAAQAEgGAGgDQAHgDAHAAQAOAAAHAHQAHAGAAAPIAAAwgAHuAlIAAgwQAAgJgEgFQgEgEgJAAQgMAAgFAGQgGAHAAAOIAAAnIgLAAIAAhqIALAAIAAAgIAAAKIAAAAQAEgFAGgEQAGgDAIAAQAOAAAHAHQAHAGAAAPIAAAwgACvAlIAAhqIAMAAIAABqgAAMAlIAAhKIAMAAIAABKgAhjAlIAAhKIALAAIAABKgAlWAlIAAgwQAAgJgEgFQgFgEgJAAQgLAAgGAGQgFAHAAAOIAAAnIgMAAIAAhKIAKAAIABAKIABAAQADgGAHgDQAGgDAIAAQANAAAHAHQAHAGAAAPIAAAwgApsAlIAAgwQAAgJgEgFQgEgEgJAAQgMAAgFAGQgGAHAAAOIAAAnIgLAAIAAhKIAJAAIACAKIAAAAQAEgGAGgDQAHgDAHAAQAOAAAHAHQAHAGAAAPIAAAwgArDAlIAAhKIAMAAIAABKgAvEAlIAAgwQAAgJgEgFQgEgEgIAAQgKAAgFAGQgFAGAAANIAAApIgMAAIAAgwQAAgJgEgFQgDgEgJAAQgKAAgFAGQgFAHAAAOIAAAnIgMAAIAAhKIAKAAIABAKIABAAQADgGAGgDQAGgDAHAAQASAAAFANIABAAQADgGAHgDQAGgEAIAAQANAAAGAHQAHAGAAAPIAAAwgA0LAlIAAhCIgOAAIAAgFIAOgEIAAgEQAAgcAYAAQAGAAAIADIgDAJQgHgCgEAAQgHAAgDAEQgDAEAAAKIAAAFIATAAIAAAIIgTAAIAABCgA3CAlIAAhKIAKAAIABANIABAAQAEgHAGgEQAGgEAHAAIAJABIgCALIgIgBQgJAAgHAHQgGAHAAALIAAAogA5AAlIgOgrIgFgTIAAAAIgFATIgOArIgOAAIgUhKIAMAAIALAqIAEAUIABAAIACgKIADgKIAOgqIAMAAIAOAqQAEAMABAIIAAAAIACgIIAOg2IAMAAIgVBKgA+/AlIAAgwQAAgJgEgFQgEgEgJAAQgMAAgFAGQgGAHAAAOIAAAnIgLAAIAAhqIALAAIAAAgIAAAKIAAAAQAEgFAGgEQAGgDAIAAQAOAAAHAHQAHAGAAAPIAAAwgEglAAAlIAAgwQAAgJgEgFQgFgEgJAAQgLAAgGAGQgFAHAAAOIAAAnIgMAAIAAhKIAKAAIABAKIABAAQADgGAHgDQAGgDAIAAQANAAAHAHQAHAGAAAPIAAAwgEgmtAAlIAAhKIAJAAIACANIAAAAQAEgHAGgEQAGgEAHAAIAJABIgBALIgJgBQgJAAgGAHQgHAHAAALIAAAogEgoeAAlIAAgwQAAgJgEgFQgEgEgJAAQgMAAgFAGQgGAHAAAOIAAAnIgLAAIAAhqIALAAIAAAgIAAAKIAAAAQAEgFAGgEQAGgDAIAAQAOAAAHAHQAHAGAAAPIAAAwgEguTAAlIAAhqIALAAIAABqgEgzlAAlIAAhKIAKAAIABANIABAAQAEgHAGgEQAGgEAHAAIAJABIgCALIgIgBQgJAAgHAHQgGAHAAALIAAAogEg3KAAlIAAhqIAMAAIAABqgEg/HAAlIAAhKIAKAAIABANIABAAQAEgHAGgEQAGgEAHAAIAJABIgCALIgIgBQgJAAgHAHQgGAHAAALIAAAogEhA+AAlIAAgwQAAgJgEgFQgEgEgIAAQgLAAgFAGQgFAGAAANIAAApIgLAAIAAgwQAAgJgEgFQgEgEgIAAQgLAAgFAGQgFAHAAAOIAAAnIgLAAIAAhKIAJAAIACAKIAAAAQAEgGAGgDQAFgDAIAAQARAAAGANIAAAAQAEgGAGgDQAGgEAJAAQAMAAAHAHQAGAGAAAPIAAAwgAOCg0QgCgCAAgEQAAgEACgCQACgBADAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQACACAAAEQAAAEgCACQAAAAgBABQAAAAgBAAQAAABgBAAQgBAAAAAAQgDAAgCgCgAANg0QgCgCAAgEQAAgEACgCQACgBADAAQABAAAAAAQABAAABAAQAAAAABABQAAAAABAAQACACAAAEQAAAEgCACQgBAAAAABQgBAAAAAAQgBABgBAAQAAAAgBAAQgDAAgCgCgAhig0QgCgCAAgEQAAgEACgCQACgBADAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQACACAAAEQAAAEgCACQAAAAgBABQAAAAgBAAQAAABgBAAQgBAAAAAAQgDAAgCgCgArCg0QgCgCAAgEQAAgEACgCQACgBADAAQABAAAAAAQABAAABAAQAAAAABABQAAAAABAAQACACAAAEQAAAEgCACQgBAAAAABQgBAAAAAAQgBABgBAAQAAAAgBAAQgDAAgCgCgAXzh4IAAhtIAJAAIACAKIAAAAQAFgGAFgDQAGgCAIAAQAPAAAIAKQAIAKAAATQAAASgIAKQgJALgOAAQgIAAgGgDQgGgDgEgFIgBAAIABAMIAAAfgAYDjWQgFAGAAAOIAAADQAAAPAFAHQAGAHALAAQAKAAAGgIQAFgIAAgOQAAgOgFgHQgGgIgKAAQgLAAgGAHgAT5h4IAAhtIAKAAIABAKIABAAQAEgGAGgDQAGgCAHAAQAPAAAIAKQAJAKAAATQAAASgJAKQgIALgPAAQgHAAgGgDQgGgDgEgFIgBAAIABAMIAAAfgAUKjWQgFAGAAAOIAAADQAAAPAFAHQAFAHAMAAQAKAAAFgIQAGgIAAgOQAAgOgGgHQgFgIgKAAQgMAAgFAHgAAGh9QgHgGAAgKQAAgHAEgFQAEgFAIgCQgDgBgCgDQgCgCAAgEQAAgEADgDQACgDAEgDQgFgDgEgFQgEgGAAgIQAAgMAIgHQAHgGAOAAQAGAAAEABIAaAAIAAAHIgOACIAEAGQABAEAAAFQAAALgHAHQgIAGgNAAIgGAAQgHADAAAGQAAADACACQADABAGAAIANAAQAMAAAHAFQAGAGAAAJQAAANgKAGQgKAHgTAAQgPAAgIgFgAAOiYQgFAEAAAHQAAAGAGADQAFADAJAAQAPAAAHgEQAGgEAAgIQAAgGgDgCQgEgCgLAAIgNAAQgIAAgEADgAAUjaQgEAFAAAIQAAAIAEAEQAEAEAIAAQARAAAAgQQAAgRgRAAQgIAAgEAEgArFh9QgIgGAAgKQAAgHAEgFQAFgFAIgCQgDgBgCgDQgCgCAAgEQAAgEACgDQACgDAFgDQgGgDgDgFQgEgGAAgIQAAgMAHgHQAIgGANAAQAGAAAFABIAaAAIAAAHIgOACIADAGQACAEAAAFQAAALgIAHQgHAGgNAAIgHAAQgHADAAAGQAAADADACQACABAGAAIAOAAQAMAAAGAFQAHAGAAAJQAAANgKAGQgKAHgTAAQgPAAgIgFgAq+iYQgEAEAAAHQAAAGAFADQAFADAKAAQAOAAAHgEQAHgEAAgIQAAgGgEgCQgEgCgKAAIgOAAQgHAAgFADgAq4jaQgEAFAAAIQAAAIAFAEQAEAEAIAAQARAAAAgQQAAgRgRAAQgIAAgFAEgAzPh9QgIgGAAgKQAAgHAFgFQAEgFAIgCQgDgBgCgDQgCgCAAgEQAAgEADgDQACgDAEgDQgFgDgEgFQgEgGAAgIQAAgMAIgHQAHgGAOAAQAGAAAEABIAaAAIAAAHIgOACIAEAGQABAEAAAFQAAALgHAHQgIAGgNAAIgGAAQgHADAAAGQAAADACACQADABAGAAIANAAQAMAAAHAFQAGAGAAAJQAAANgKAGQgKAHgTAAQgPAAgIgFgAzHiYQgFAEAAAHQAAAGAGADQAFADAJAAQAPAAAHgEQAGgEAAgIQAAgGgDgCQgEgCgLAAIgNAAQgIAAgEADgAzBjaQgEAFAAAIQAAAIAEAEQAEAEAIAAQARAAAAgQQAAgRgRAAQgIAAgEAEgA4lh4IAAhtIAKAAIABAKIABAAQAEgGAGgDQAGgCAHAAQAPAAAIAKQAJAKAAATQAAASgJAKQgIALgPAAQgHAAgGgDQgGgDgEgFIgBAAIABAMIAAAfgA4UjWQgFAGAAAOIAAADQAAAPAFAHQAFAHAMAAQAKAAAFgIQAGgIAAgOQAAgOgGgHQgFgIgKAAQgMAAgFAHgEgmtgB4IAAhtIAKAAIABAKIABAAQAEgGAGgDQAGgCAHAAQAPAAAIAKQAJAKAAATQAAASgJAKQgIALgPAAQgHAAgGgDQgGgDgEgFIgBAAIABAMIAAAfgEgmcgDWQgFAGAAAOIAAADQAAAPAFAHQAFAHAMAAQAKAAAFgIQAGgIAAgOQAAgOgGgHQgFgIgKAAQgMAAgFAHgEguqgB4IAAhtIAJAAIACAKIAAAAQAFgGAFgDQAGgCAIAAQAPAAAIAKQAIAKAAATQAAASgIAKQgJALgOAAQgIAAgGgDQgGgDgEgFIgBAAIABAMIAAAfgEguagDWQgFAGAAAOIAAADQAAAPAFAHQAGAHALAAQAKAAAGgIQAFgIAAgOQAAgOgFgHQgGgIgKAAQgLAAgGAHgEAtTgCaQgCgCAAgFQAAgFACgCQACgCAEAAQAEAAACACQACACAAAFQAAAEgCADQgCACgEAAQgEAAgCgCgEBAHgCvIAAgtIgLAAIAAgGIALgEIAEgQIAHAAIAAARIAWAAIAAAJIgWAAIAAAsQAAAHADAEQADADAGAAIAGAAIAEgBIAAAJIgFABIgHABQgVAAAAgXgEA+4gCeQgGgGAAgLQAAgWAkgBIANgBIAAgEQAAgJgEgFQgEgEgIAAQgJAAgMAGIgEgJQAGgDAGgBQAHgCAHAAQANAAAHAGQAGAGAAANIAAAzIgIAAIgDgKIAAAAQgGAHgFACQgGADgIAAQgMAAgGgGgEA/XgC+QgNAAgGAEQgGAEAAAIQAAAGADADQAEADAHAAQAKAAAHgGQAGgFAAgLIAAgHgEA8xgCvIAAgtIgLAAIAAgGIALgEIAEgQIAHAAIAAARIAWAAIAAAJIgWAAIAAAsQAAAHADAEQADADAGAAIAGAAIAEgBIAAAJIgFABIgHABQgVAAAAgXgEA7DgCdQgIgFgEgJQgEgJAAgLQAAgTAJgKQAJgKAQAAQAQAAAJAKQAKALAAASQAAASgKAKQgJALgQAAQgKAAgIgFgEA7EgDVQgGAHAAAPQAAAOAGAIQAGAHALAAQALAAAGgHQAGgIAAgOQAAgPgGgHQgGgIgLAAQgLAAgGAIgEA5vgCdIAAgLQAFADAGACIAMABQAJAAAFgDQAFgCAAgGQAAgFgEgDQgEgDgLgEIgPgHQgEgDgCgEQgCgDAAgFQAAgKAHgFQAHgFAOAAQAMAAALAFIgEAJQgLgFgJAAQgIAAgFADQgEACAAAFQAAADACACQABACAEACIANAGQANAEAFAFQAFAFAAAIQAAAKgIAGQgIAGgOAAQgPAAgIgFgEA4HgCdIAAgLQAGADAGACIAMABQAJAAAFgDQAEgCAAgGQAAgFgDgDQgEgDgLgEIgPgHQgFgDgCgEQgCgDAAgFQAAgKAHgFQAIgFANAAQAMAAAMAFIgEAJQgMgFgJAAQgIAAgEADQgEACAAAFQAAADABACQACACADACIAOAGQANAEAFAFQAEAFAAAIQAAAKgHAGQgIAGgOAAQgPAAgJgFgEA1hgCvIAAgtIgLAAIAAgGIALgEIAFgQIAHAAIAAARIAVAAIAAAJIgVAAIAAAsQAAAHADAEQADADAGAAIAFAAIAFgBIAAAJIgGABIgGABQgWAAAAgXgEAzzgCdQgHgFgFgJQgEgJAAgLQAAgTAJgKQAKgKAQAAQAQAAAJAKQAJALAAASQAAASgJAKQgJALgRAAQgKAAgIgFgEAz1gDVQgGAHAAAPQAAAOAGAIQAFAHAMAAQALAAAGgHQAFgIAAgOQAAgPgFgHQgGgIgLAAQgMAAgFAIgEAyVgCiQgIgLAAgSQAAgTAIgKQAJgKAOAAQAQAAAIALIABAAIgBgLIAAgeIALAAIAABqIgJAAIgBgKIgBAAQgIAMgQAAQgOAAgJgKgEAyegDVQgFAIAAAOQAAAOAFAIQAGAHAKAAQALAAAGgGQAFgHAAgOIAAgCQAAgQgFgHQgGgHgLAAQgKAAgGAIgEAwjgCjQgJgKAAgSQAAgSAJgLQAJgKAPAAQAOAAAIAJQAIAJAAAQIAAAHIg0AAQABANAGAHQAGAHAMAAQAMAAAMgFIAAAKIgLAEIgNABQgRAAgKgLgEAwsgDXQgFAGgBAKIAnAAQAAgKgFgGQgFgGgIAAQgKAAgFAGgEAsAgCiQgIgLAAgSQAAgTAIgKQAIgKAPAAQAPAAAIALIABAAIgBgLIAAgeIAMAAIAABqIgJAAIgCgKIgBAAQgIAMgPAAQgPAAgIgKgEAsJgDVQgGAIAAAOQAAAOAGAIQAFAHAKAAQAMAAAFgGQAFgHAAgOIAAgCQAAgQgFgHQgFgHgMAAQgKAAgFAIgEApWgCdQgHgFgFgJQgEgJAAgLQAAgTAJgKQAKgKAQAAQAQAAAJAKQAJALAAASQAAASgJAKQgJALgRAAQgKAAgIgFgEApYgDVQgGAHAAAPQAAAOAGAIQAFAHAMAAQALAAAGgHQAFgIAAgOQAAgPgFgHQgGgIgLAAQgMAAgFAIgEAlvgCjQgKgKAAgSQAAgSAJgLQAJgKAPAAQAOAAAJAJQAIAJAAAQIAAAHIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgLgEAl4gDXQgGAGgBAKIAoAAQAAgKgFgGQgFgGgJAAQgJAAgFAGgEAjjgCvIAAgtIgLAAIAAgGIALgEIAEgQIAHAAIAAARIAWAAIAAAJIgWAAIAAAsQAAAHADAEQADADAGAAIAGAAIAEgBIAAAJIgFABIgHABQgVAAAAgXgEAg6gCjQgJgKAAgSQAAgSAJgLQAJgKAPAAQAOAAAIAJQAIAJAAAQIAAAHIg0AAQABANAGAHQAGAHAMAAQAMAAAMgFIAAAKIgLAEIgNABQgRAAgKgLgEAhDgDXQgFAGgBAKIAnAAQAAgKgFgGQgFgGgIAAQgKAAgFAGgAemidQgIgFgEgJQgEgJAAgLQAAgTAJgKQAJgKAQAAQAQAAAJAKQAKALAAASQAAASgKAKQgJALgQAAQgKAAgIgFgAenjVQgGAHAAAPQAAAOAGAIQAGAHALAAQALAAAGgHQAGgIAAgOQAAgPgGgHQgGgIgLAAQgLAAgGAIgAbhieQgHgGAAgLQAAgWAlgBIAMgBIAAgEQAAgJgDgFQgEgEgJAAQgJAAgMAGIgDgJQAFgDAHgBQAGgCAHAAQAOAAAGAGQAHAGAAANIAAAzIgJAAIgCgKIgBAAQgFAHgGACQgGADgIAAQgLAAgGgGgAcAi+QgOAAgGAEQgGAEAAAIQAAAGAEADQAEADAGAAQALAAAGgGQAGgFAAgLIAAgHgAZyijQgJgKAAgSQAAgSAJgLQAJgKAPAAQAOAAAIAJQAIAJAAAQIAAAHIg0AAQABANAGAHQAGAHAMAAQAMAAAMgFIAAAKIgLAEIgNABQgRAAgKgLgAZ7jXQgFAGgBAKIAnAAQAAgKgFgGQgFgGgIAAQgKAAgFAGgAWqidQgHgFgFgJQgEgJAAgLQAAgTAJgKQAKgKAQAAQAQAAAJAKQAJALAAASQAAASgJAKQgJALgRAAQgKAAgIgFgAWsjVQgGAHAAAPQAAAOAGAIQAFAHAMAAQALAAAGgHQAFgIAAgOQAAgPgFgHQgGgIgLAAQgMAAgFAIgAVVijQgKgKAAgSQAAgSAJgLQAJgKAPAAQAOAAAJAJQAIAJAAAQIAAAHIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgLgAVejXQgGAGgBAKIAoAAQAAgKgFgGQgFgGgJAAQgJAAgFAGgARcidQgHgFgFgJQgEgJAAgLQAAgTAJgKQAKgKAQAAQAQAAAJAKQAJALAAASQAAASgJAKQgJALgRAAQgKAAgIgFgARejVQgGAHAAAPQAAAOAGAIQAFAHAMAAQALAAAGgHQAFgIAAgOQAAgPgFgHQgGgIgLAAQgMAAgFAIgAPkidIAAgLQAGADAGACIAMABQAJAAAFgDQAEgCAAgGQAAgFgDgDQgEgDgLgEIgPgHQgFgDgCgEQgCgDAAgFQAAgKAHgFQAIgFANAAQAMAAAMAFIgEAJQgMgFgJAAQgIAAgEADQgEACAAAFQAAADABACQACACADACIAOAGQANAEAFAFQAEAFAAAIQAAAKgHAGQgIAGgOAAQgPAAgJgFgAOXiiQgIgLAAgSQAAgTAIgKQAIgKAPAAQAPAAAIALIABAAIgBgLIAAgeIAMAAIAABqIgJAAIgCgKIgBAAQgIAMgPAAQgPAAgIgKgAOgjVQgGAIAAAOQAAAOAGAIQAFAHAKAAQAMAAAFgGQAFgHAAgOIAAgCQAAgQgFgHQgFgHgMAAQgKAAgFAIgALwieQgHgGAAgLQAAgWAlgBIAMgBIAAgEQAAgJgDgFQgEgEgJAAQgJAAgMAGIgDgJQAFgDAHgBQAGgCAHAAQAOAAAGAGQAHAGAAANIAAAzIgJAAIgCgKIgBAAQgFAHgGACQgGADgIAAQgLAAgGgGgAMPi+QgOAAgGAEQgGAEAAAIQAAAGAEADQAEADAGAAQALAAAGgGQAGgFAAgLIAAgHgAIrijQgKgKAAgSQAAgSAJgLQAJgKAPAAQAOAAAJAJQAIAJAAAQIAAAHIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgLgAI0jXQgGAGgBAKIAoAAQAAgKgFgGQgFgGgJAAQgJAAgFAGgAGeivIAAgtIgLAAIAAgGIALgEIAFgQIAHAAIAAARIAVAAIAAAJIgVAAIAAAsQAAAHADAEQADADAGAAIAFAAIAFgBIAAAJIgGABIgGABQgWAAAAgXgAEwidQgHgFgFgJQgEgJAAgLQAAgTAJgKQAKgKAQAAQAQAAAJAKQAJALAAASQAAASgJAKQgJALgRAAQgKAAgIgFgAEyjVQgGAHAAAPQAAAOAGAIQAFAHAMAAQALAAAGgHQAFgIAAgOQAAgPgFgHQgGgIgLAAQgMAAgFAIgAD0ivIAAgtIgLAAIAAgGIALgEIAEgQIAHAAIAAARIAWAAIAAAJIgWAAIAAAsQAAAHADAEQADADAGAAIAGAAIAEgBIAAAJIgFABIgHABQgVAAAAgXgAkIieQgGgGAAgLQAAgWAkgBIANgBIAAgEQAAgJgEgFQgEgEgIAAQgJAAgMAGIgEgJQAGgDAGgBQAHgCAHAAQANAAAHAGQAGAGAAANIAAAzIgIAAIgDgKIAAAAQgGAHgFACQgGADgIAAQgMAAgGgGgAjpi+QgNAAgGAEQgGAEAAAIQAAAGADADQAEADAHAAQAKAAAHgGQAGgFAAgLIAAgHgAohieQgGgGAAgLQAAgWAkgBIANgBIAAgEQAAgJgEgFQgEgEgIAAQgJAAgMAGIgEgJQAGgDAGgBQAHgCAHAAQANAAAHAGQAGAGAAANIAAAzIgIAAIgDgKIAAAAQgGAHgFACQgGADgIAAQgMAAgGgGgAoCi+QgNAAgGAEQgGAEAAAIQAAAGADADQAEADAHAAQAKAAAHgGQAGgFAAgLIAAgHgApSivIAAgtIgLAAIAAgGIALgEIAEgQIAHAAIAAARIAWAAIAAAJIgWAAIAAAsQAAAHADAEQADADAGAAIAGAAIAEgBIAAAJIgFABIgHABQgVAAAAgXgAs5iiQgIgLAAgSQAAgTAIgKQAIgKAPAAQAPAAAIALIABAAIgBgLIAAgeIAMAAIAABqIgJAAIgCgKIgBAAQgIAMgPAAQgPAAgIgKgAswjVQgGAIAAAOQAAAOAGAIQAFAHAKAAQAMAAAFgGQAFgHAAgOIAAgCQAAgQgFgHQgFgHgMAAQgKAAgFAIgAu0iiQgIgLAAgSQAAgTAIgKQAJgKAOAAQAQAAAIALIABAAIgBgLIAAgeIALAAIAABqIgJAAIgBgKIgBAAQgIAMgQAAQgOAAgJgKgAurjVQgFAIAAAOQAAAOAFAIQAGAHAKAAQALAAAGgGQAFgHAAgOIAAgCQAAgQgFgHQgGgHgLAAQgKAAgGAIgAxbieQgHgGAAgLQAAgWAlgBIAMgBIAAgEQAAgJgDgFQgEgEgJAAQgJAAgMAGIgDgJQAFgDAHgBQAGgCAHAAQAOAAAGAGQAHAGAAANIAAAzIgJAAIgCgKIgBAAQgFAHgGACQgGADgIAAQgLAAgGgGgAw8i+QgOAAgGAEQgGAEAAAIQAAAGAEADQAEADAGAAQALAAAGgGQAGgFAAgLIAAgHgA14ivIAAgtIgLAAIAAgGIALgEIAFgQIAHAAIAAARIAVAAIAAAJIgVAAIAAAsQAAAHADAEQADADAGAAIAFAAIAFgBIAAAJIgGABIgGABQgWAAAAgXgA3JifQgGgGAAgPIAAgxIALAAIAAAxQAAAJAEAFQAEAEAJAAQAMAAAGgGQAFgHAAgOIAAgoIALAAIAABLIgJAAIgCgKIAAAAQgEAGgGADQgGADgIAAQgOAAgHgHgA7widQgIgFgEgJQgEgJAAgLQAAgTAJgKQAJgKAQAAQAQAAAJAKQAKALAAASQAAASgKAKQgJALgQAAQgKAAgIgFgA7vjVQgGAHAAAPQAAAOAGAIQAGAHALAAQALAAAGgHQAGgIAAgOQAAgPgGgHQgGgIgLAAQgLAAgGAIgA86iiQgJgKAAgTQAAgTAJgKQAJgKARAAIAKABIAJADIgEAJIgIgCIgIgBQgXAAAAAdQAAAOAGAHQAGAIALAAQAJAAAKgEIAAAKQgIAEgLAAQgQAAgJgKgA/cidQgHgFgFgJQgEgJAAgLQAAgTAJgKQAKgKAQAAQAQAAAJAKQAJALAAASQAAASgJAKQgJALgRAAQgKAAgIgFgA/ajVQgGAHAAAPQAAAOAGAIQAFAHAMAAQALAAAGgHQAFgIAAgOQAAgPgFgHQgGgIgLAAQgMAAgFAIgEgiPgCjQgKgKAAgSQAAgSAJgLQAJgKAPAAQAOAAAJAJQAIAJAAAQIAAAHIg0AAQAAANAHAHQAGAHALAAQANAAAMgFIAAAKIgMAEIgNABQgRAAgJgLgEgiGgDXQgGAGgBAKIAoAAQAAgKgFgGQgFgGgJAAQgJAAgFAGgEglLgCdQgHgFgFgJQgEgJAAgLQAAgTAJgKQAKgKAQAAQAQAAAJAKQAJALAAASQAAASgJAKQgJALgRAAQgKAAgIgFgEglJgDVQgGAHAAAPQAAAOAGAIQAFAHAMAAQALAAAGgHQAFgIAAgOQAAgPgFgHQgGgIgLAAQgMAAgFAIgEgobgCjQgJgKAAgSQAAgSAJgLQAJgKAPAAQAOAAAIAJQAIAJAAAQIAAAHIg0AAQABANAGAHQAGAHAMAAQAMAAAMgFIAAAKIgLAEIgNABQgRAAgKgLgEgoSgDXQgFAGgBAKIAnAAQAAgKgFgGQgFgGgIAAQgKAAgFAGgEgqngCvIAAgtIgLAAIAAgGIALgEIAFgQIAHAAIAAARIAVAAIAAAJIgVAAIAAAsQAAAHADAEQADADAGAAIAFAAIAFgBIAAAJIgGABIgGABQgWAAAAgXgEgr9gCvIAAgtIgLAAIAAgGIALgEIAEgQIAHAAIAAARIAWAAIAAAJIgWAAIAAAsQAAAHADAEQADADAGAAIAGAAIAEgBIAAAJIgFABIgHABQgVAAAAgXgEgtOgCfQgHgGAAgPIAAgxIAMAAIAAAxQAAAJAEAFQAEAEAJAAQAMAAAFgGQAGgHAAgOIAAgoIALAAIAABLIgJAAIgCgKIgBAAQgDAGgGADQgHADgIAAQgNAAgHgHgEgwXgCdQgIgFgEgJQgEgJAAgLQAAgTAJgKQAJgKAQAAQAQAAAJAKQAKALAAASQAAASgKAKQgJALgQAAQgKAAgIgFgEgwWgDVQgGAHAAAPQAAAOAGAIQAGAHALAAQALAAAGgHQAGgIAAgOQAAgPgGgHQgGgIgLAAQgLAAgGAIgEgxUgCvIAAgtIgLAAIAAgGIALgEIAFgQIAHAAIAAARIAVAAIAAAJIgVAAIAAAsQAAAHADAEQADADAGAAIAFAAIAFgBIAAAJIgGABIgGABQgWAAAAgXgEgzBgCdIAAgLQAFADAGACIAMABQAJAAAFgDQAFgCAAgGQAAgFgEgDQgEgDgLgEIgPgHQgEgDgCgEQgCgDAAgFQAAgKAHgFQAHgFAOAAQAMAAALAFIgEAJQgLgFgJAAQgIAAgFADQgEACAAAFQAAADACACQABACAEACIANAGQANAEAFAFQAFAFAAAIQAAAKgIAGQgIAGgOAAQgPAAgIgFgEg2jgCdQgIgFgEgJQgEgJAAgLQAAgTAJgKQAJgKAQAAQAQAAAJAKQAKALAAASQAAASgKAKQgJALgQAAQgKAAgIgFgEg2igDVQgGAHAAAPQAAAOAGAIQAGAHALAAQALAAAGgHQAGgIAAgOQAAgPgGgHQgGgIgLAAQgLAAgGAIgEg4bgCdIAAgLQAGADAGACIAMABQAJAAAFgDQAEgCAAgGQAAgFgDgDQgEgDgLgEIgPgHQgFgDgCgEQgCgDAAgFQAAgKAHgFQAIgFANAAQAMAAAMAFIgEAJQgMgFgJAAQgIAAgEADQgEACAAAFQAAADABACQACACADACIAOAGQANAEAFAFQAEAFAAAIQAAAKgHAGQgIAGgOAAQgPAAgJgFgEg5egCdIAAgLQAGADAGACIAMABQAJAAAFgDQAEgCAAgGQAAgFgDgDQgEgDgLgEIgPgHQgFgDgCgEQgCgDAAgFQAAgKAHgFQAIgFANAAQAMAAAMAFIgEAJQgMgFgJAAQgIAAgEADQgEACAAAFQAAADABACQACACADACIAOAGQANAEAFAFQAEAFAAAIQAAAKgHAGQgIAGgOAAQgPAAgJgFgEg+ugCfQgGgGAAgPIAAgxIALAAIAAAxQAAAJAEAFQAEAEAJAAQAMAAAGgGQAFgHAAgOIAAgoIALAAIAABLIgJAAIgCgKIAAAAQgEAGgGADQgGADgIAAQgOAAgHgHgEhAZgCmQgMgNAAgZQAAgZAMgNQAMgOAXAAQAVAAAMAOQANAOAAAYQAAAYgNAOQgMAOgVAAQgXAAgMgOgEhAQgDrQgIALAAAUQAAAUAIALQAJAKARAAQAQAAAJgKQAIgLAAgUQAAgUgIgLQgJgKgQAAQgRAAgJAKgEA+VgCaIAAgwQAAgKgEgEQgFgFgJAAQgLAAgGAHQgFAGAAAPIAAAnIgMAAIAAhqIAMAAIAAAgIgBAJIABAAQADgFAGgDQAHgDAIAAQANAAAHAGQAHAHAAAOIAAAxgEA3ogCaIAAhLIAMAAIAABLgEA3GgCaIAAgwQAAgKgEgEQgFgFgJAAQgLAAgGAHQgFAGAAAPIAAAnIgMAAIAAhqIAMAAIAAAgIgBAJIABAAQADgFAGgDQAHgDAIAAQANAAAHAGQAHAHAAAOIAAAxgEAvqgCaIgVhDIgDgLIgCgIQgBAJgEAKIgTBDIgMAAIgahkIAMAAIAQA+QADANACALQABgNAEgMIASg9IAMAAIATA9QAEALACAOIAFgYIAQg+IAMAAIgbBkgEArYgCaIAAhqIAMAAIAABqgEAqfgCaIAAhLIAJAAIACAOIAAAAQAEgHAGgEQAGgEAHAAIAJABIgBAKIgJgBQgJAAgGAHQgHAIAAALIAAAogEAoagCaIgOgsIgEgSIgBAAIgFASIgOAsIgNAAIgVhLIAMAAIALArIAFAUIAAAAIADgKIADgKIANgrIANAAIANArQAEAMABAIIABAAIABgIIAPg3IAMAAIgVBLgEAlHgCaIAAgwQAAgKgEgEQgFgFgJAAQgLAAgGAHQgFAGAAAPIAAAnIgMAAIAAhqIAMAAIAAAgIgBAJIABAAQADgFAGgDQAHgDAIAAQANAAAHAGQAHAHAAAOIAAAxgEAiEgCaIAAhLIAJAAIACAOIAAAAQAEgHAGgEQAGgEAHAAIAJABIgBAKIgJgBQgJAAgGAHQgHAIAAALIAAAogAf/iaIgdhLIAMAAIARAtIAGAUIABAAIAEgPIASgyIANAAIgdBLgAdSiaIAAhqIALAAIAABqgAcuiaIAAhqIAMAAIAABqgAZJiaIAAhqIALAAIAABqgASpiaIAAhCIgOAAIAAgFIAOgEIAAgFQAAgbAYAAQAGAAAIACIgDAJQgHgCgEAAQgHAAgDAEQgDAFAAAJIAAAFIATAAIAAAJIgTAAIAABCgANwiaIAAgwQAAgKgEgEQgEgFgJAAQgMAAgFAHQgGAGAAAPIAAAnIgLAAIAAhLIAJAAIACAKIAAAAQAEgFAGgDQAHgDAHAAQAOAAAHAGQAHAHAAAOIAAAxgALMiaIAAgwQAAgKgEgEQgEgFgJAAQgMAAgFAHQgGAGAAAPIAAAnIgLAAIAAhqIALAAIAAAgIAAAJIAAAAQAEgFAGgDQAGgDAIAAQAOAAAHAGQAHAHAAAOIAAAxgAIDiaIAAgwQAAgKgEgEQgFgFgJAAQgLAAgGAHQgFAGAAAPIAAAnIgMAAIAAhqIAMAAIAAAgIgBAJIABAAQADgFAGgDQAHgDAIAAQANAAAHAGQAHAHAAAOIAAAxgADQiaIAAgwQAAgKgEgEQgEgFgJAAQgMAAgFAHQgGAGAAAPIAAAnIgLAAIAAhLIAJAAIACAKIAAAAQAEgFAGgDQAHgDAHAAQAOAAAHAGQAHAHAAAOIAAAxgAB5iaIAAhLIALAAIAABLgAgaiaIAAgwQAAgKgEgEQgEgFgJAAQgMAAgFAHQgGAGAAAPIAAAnIgLAAIAAhLIAJAAIACAKIAAAAQAEgFAGgDQAHgDAHAAQAOAAAHAGQAHAHAAAOIAAAxgAhxiaIAAhLIAMAAIAABLgAiMiaIgbgjIgIAHIAAAcIgMAAIAAhqIAMAAIAAA4IgBAMIABAAIAJgLIAYgaIANAAIgeAgIAgArgAksiaIAAgxQAAgJgEgEQgEgFgIAAQgKAAgFAGQgFAHAAAMIAAAqIgMAAIAAgxQAAgJgEgEQgDgFgJAAQgKAAgFAHQgFAGAAAPIAAAnIgMAAIAAhLIAKAAIABAKIABAAQADgFAGgDQAGgDAHAAQASAAAFAMIABAAQADgFAHgEQAGgDAIAAQANAAAGAGQAHAHAAAOIAAAxgAnUiaIAAhqIAMAAIAABqgAp3iaIAAhLIALAAIAABLgArniaIAAhLIALAAIAABLgAvbiaIAAgwQAAgKgEgEQgEgFgJAAQgMAAgFAHQgGAGAAAPIAAAnIgLAAIAAhLIAJAAIACAKIAAAAQAEgFAGgDQAHgDAHAAQAOAAAHAGQAHAHAAAOIAAAxgAzwiaIAAgwQAAgKgEgEQgFgFgJAAQgLAAgGAHQgFAGAAAPIAAAnIgMAAIAAhLIAKAAIABAKIABAAQADgFAHgDQAGgDAIAAQANAAAHAGQAHAHAAAOIAAAxgA1HiaIAAhLIALAAIAABLgA5IiaIAAgxQAAgJgEgEQgEgFgIAAQgKAAgFAGQgFAHAAAMIAAAqIgMAAIAAgxQAAgJgEgEQgDgFgJAAQgKAAgFAHQgFAGAAAPIAAAnIgMAAIAAhLIAKAAIABAKIABAAQADgFAGgDQAGgDAHAAQASAAAFAMIABAAQADgFAHgEQAGgDAIAAQANAAAGAGQAHAHAAAOIAAAxgA+PiaIAAhCIgOAAIAAgFIAOgEIAAgFQAAgbAYAAQAGAAAIACIgDAJQgHgCgEAAQgHAAgDAEQgDAFAAAJIAAAFIATAAIAAAJIgTAAIAABCgEghGgCaIAAhLIAKAAIABAOIABAAQAEgHAGgEQAGgEAHAAIAJABIgCAKIgIgBQgJAAgHAHQgGAIAAALIAAAogEgjFgCaIgOgsIgEgSIgBAAIgFASIgOAsIgNAAIgVhLIAMAAIALArIAFAUIAAAAIADgKIADgKIANgrIANAAIANArQAEAMABAIIABAAIABgIIAPg3IAMAAIgVBLgEgpDgCaIAAgwQAAgKgEgEQgEgFgJAAQgMAAgFAHQgGAGAAAPIAAAnIgLAAIAAhqIALAAIAAAgIAAAJIAAAAQAEgFAGgDQAGgDAIAAQAOAAAHAGQAHAHAAAOIAAAxgEgzggCaIAAhLIALAAIAABLgEg0ngCaIAAgwQAAgKgEgEQgFgFgJAAQgLAAgGAHQgFAGAAAPIAAAnIgMAAIAAhLIAKAAIABAKIABAAQADgFAHgDQAGgDAIAAQANAAAHAGQAHAHAAAOIAAAxgEg3TgCaIAAhLIAMAAIAABLgEg59gCaIAAhLIAMAAIAABLgEg6ggCaIAAgxQAAgJgEgEQgEgFgIAAQgKAAgFAGQgFAHAAAMIAAAqIgMAAIAAgxQAAgJgEgEQgDgFgJAAQgKAAgFAHQgFAGAAAPIAAAnIgMAAIAAhLIAKAAIABAKIABAAQADgFAGgDQAGgDAHAAQASAAAFAMIABAAQADgFAHgEQAGgDAIAAQANAAAGAGQAHAHAAAOIAAAxgEg9egCaIAAhLIAKAAIABAOIABAAQAEgHAGgEQAGgEAHAAIAJABIgCAKIgIgBQgJAAgHAHQgGAIAAALIAAAogEA3pgD0QgCgBAAgEQAAgEACgCQACgCADAAQABAAAAAAQABAAABABQAAAAABAAQAAAAABABQACACAAAEQAAAEgCABQgBABAAAAQgBABAAAAQgBAAgBAAQAAAAgBAAQgDAAgCgCgAB6j0QgCgBAAgEQAAgEACgCQACgCADAAQAAAAABAAQABAAAAABQABAAAAAAQABAAAAABQACACAAAEQAAAEgCABQAAABgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgDAAgCgCgAhwj0QgCgBAAgEQAAgEACgCQACgCADAAQABAAAAAAQABAAABABQAAAAABAAQAAAAABABQACACAAAEQAAAEgCABQgBABAAAAQgBABAAAAQgBAAgBAAQAAAAgBAAQgDAAgCgCgAp2j0QgCgBAAgEQAAgEACgCQACgCADAAQAAAAABAAQABAAAAABQABAAAAAAQABAAAAABQACACAAAEQAAAEgCABQAAABgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgDAAgCgCgArmj0QgCgBAAgEQAAgEACgCQACgCADAAQAAAAABAAQABAAAAABQABAAAAAAQABAAAAABQACACAAAEQAAAEgCABQAAABgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgDAAgCgCgA1Gj0QgCgBAAgEQAAgEACgCQACgCADAAQAAAAABAAQABAAAAABQABAAAAAAQABAAAAABQACACAAAEQAAAEgCABQAAABgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgDAAgCgCgEgzfgD0QgCgBAAgEQAAgEACgCQACgCADAAQAAAAABAAQABAAAAABQABAAAAAAQABAAAAABQACACAAAEQAAAEgCABQAAABgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgDAAgCgCgEg3SgD0QgCgBAAgEQAAgEACgCQACgCADAAQABAAAAAAQABAAABABQAAAAABAAQAAAAABABQACACAAAEQAAAEgCABQgBABAAAAQgBABAAAAQgBAAgBAAQAAAAgBAAQgDAAgCgCgEg58gD0QgCgBAAgEQAAgEACgCQACgCADAAQABAAAAAAQABAAABABQAAAAABAAQAAAAABABQACACAAAEQAAAEgCABQgBABAAAAQgBABAAAAQgBAAgBAAQAAAAgBAAQgDAAgCgCg");
        this.shape.setTransform(609.875, 902.575);

        this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

        // Rp3_title
        this.rp3TitleSplash = new lib.Rp3Title();
        this.rp3TitleSplash.name = "rp3TitleSplash";
        this.rp3TitleSplash.parent = this;
        this.rp3TitleSplash.setTransform(916, 360.25, 0.8696, 0.8696);

        this.timeline.addTween(cjs.Tween.get(this.rp3TitleSplash).wait(1));

        // Rp4_title
        this.rp4TitleSplash = new lib.Rp4Title();
        this.rp4TitleSplash.name = "rp4TitleSplash";
        this.rp4TitleSplash.parent = this;
        this.rp4TitleSplash.setTransform(304.75, 360.1, 0.8696, 0.8696);

        this.timeline.addTween(cjs.Tween.get(this.rp4TitleSplash).wait(1));

    }).prototype = p = new cjs.MovieClip();
    p.nominalBounds = new cjs.Rectangle(664.2, 543.8, 495.29999999999995, 385);
    // library properties:
    lib.properties = {
        id: '06CA646165B9954D8AB99D566BA018F3',
        width: 1218,
        height: 1000,
        fps: 30,
        color: "#FFFFFF",
        opacity: 1.00,
        manifest: [
            {
                src: "images/mm4_splashpage_atlas_.png?1562932135505",
                id: "mm4_splashpage_atlas_"
            }
	],
        preloads: []
    };



    // bootstrap callback support:

    (lib.Stage = function (canvas) {
        createjs.Stage.call(this, canvas);
    }).prototype = p = new createjs.Stage();

    p.setAutoPlay = function (autoPlay) {
        this.tickEnabled = autoPlay;
    }
    p.play = function () {
        this.tickEnabled = true;
        this.getChildAt(0).gotoAndPlay(this.getTimelinePosition())
    }
    p.stop = function (ms) {
        if (ms) this.seek(ms);
        this.tickEnabled = false;
    }
    p.seek = function (ms) {
        this.tickEnabled = true;
        this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000);
    }
    p.getDuration = function () {
        return this.getChildAt(0).totalFrames / lib.properties.fps * 1000;
    }

    p.getTimelinePosition = function () {
        return this.getChildAt(0).currentFrame / lib.properties.fps * 1000;
    }

    an.bootcompsLoaded = an.bootcompsLoaded || [];
    if (!an.bootstrapListeners) {
        an.bootstrapListeners = [];
    }

    an.bootstrapCallback = function (fnCallback) {
        an.bootstrapListeners.push(fnCallback);
        if (an.bootcompsLoaded.length > 0) {
            for (var i = 0; i < an.bootcompsLoaded.length; ++i) {
                fnCallback(an.bootcompsLoaded[i]);
            }
        }
    };

    an.compositions = an.compositions || {};
    an.compositions['06CA646165B9954D8AB99D566BA018F3'] = {
        getStage: function () {
            return exportRoot.getStage();
        },
        getLibrary: function () {
            return lib;
        },
        getSpriteSheet: function () {
            return ss;
        },
        getImages: function () {
            return img;
        }
    };

    an.compositionLoaded = function (id) {
        an.bootcompsLoaded.push(id);
        for (var j = 0; j < an.bootstrapListeners.length; j++) {
            an.bootstrapListeners[j](id);
        }
    }

    an.getComposition = function (id) {
        return an.compositions[id];
    }


    an.makeResponsive = function (isResp, respDim, isScale, scaleType, domContainers) {
        var lastW, lastH, lastS = 1;
        window.addEventListener('resize', resizeCanvas);
        resizeCanvas();

        function resizeCanvas() {
            var w = lib.properties.width,
                h = lib.properties.height;
            var iw = window.innerWidth,
                ih = window.innerHeight;
            var pRatio = window.devicePixelRatio || 1,
                xRatio = iw / w,
                yRatio = ih / h,
                sRatio = 1;
            if (isResp) {
                if ((respDim == 'width' && lastW == iw) || (respDim == 'height' && lastH == ih)) {
                    sRatio = lastS;
                } else if (!isScale) {
                    if (iw < w || ih < h)
                        sRatio = Math.min(xRatio, yRatio);
                } else if (scaleType == 1) {
                    sRatio = Math.min(xRatio, yRatio);
                } else if (scaleType == 2) {
                    sRatio = Math.max(xRatio, yRatio);
                }
            }
            domContainers[0].width = w * pRatio * sRatio;
            domContainers[0].height = h * pRatio * sRatio;
            domContainers.forEach(function (container) {
                container.style.width = w * sRatio + 'px';
                container.style.height = h * sRatio + 'px';
            });
            stage.scaleX = pRatio * sRatio;
            stage.scaleY = pRatio * sRatio;
            lastW = iw;
            lastH = ih;
            lastS = sRatio;
            stage.tickOnUpdate = false;
            stage.update();
            stage.tickOnUpdate = true;
        }
    }


})(createjs = createjs || {}, AdobeAn = AdobeAn || {});
var createjs, AdobeAn;